"use strict";
const assert=require("node:assert/strict");const fs=require("node:fs");const http=require("node:http");const os=require("node:os");const path=require("node:path");const test=require("node:test");
const startServer=require("../shared/server/start-authoritative-game-server");const {createMemoryRoomStore}=require("../shared/server/memory-room-store");const {createSqliteRoomStore}=require("../shared/server/sqlite-room-store");
async function post(base,pathname,body){const response=await fetch(`${base}${pathname}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});return{response,payload:await response.json()};}
const auth=(session,extras={})=>({roomCode:session.roomCode,playerId:session.clientId,resumeToken:session.resumeToken,...extras});
function events(base,session){return new Promise((resolve,reject)=>{const url=new URL("/api/events",base);for(const key of["clientId","roomCode","resumeToken"])url.searchParams.set(key,session[key]);const request=http.get(url,(response)=>response.statusCode===200?response.once("data",()=>resolve(request)):reject(new Error(`SSE ${response.statusCode}`)));request.on("error",reject);});}
async function launch(options={}){const engine=await import("./server/game-engine.mjs");const store=options.roomStore||createMemoryRoomStore();const server=startServer({gameRoot:__dirname,sharedRoot:path.resolve(__dirname,"../shared"),engine,protocolVersion:3,defaultPort:0,spectatorsEnabled:true,spectatorLimit:10,roomStore:store});await new Promise((resolve)=>server.once("listening",resolve));return{server,store,base:`http://127.0.0.1:${server.address().port}`};}
async function close(running,streams=[]){streams.forEach((stream)=>stream.destroy());await new Promise((resolve)=>setImmediate(resolve));await new Promise((resolve)=>{running.server.close(resolve);running.server.closeAllConnections?.();});}
async function create(running,capacity=2){return(await post(running.base,"/api/rooms",{hostId:"host",name:"房主",capacity})).payload;}
async function action(running,session,id,value){return post(running.base,"/api/actions",auth(session,{actionId:id,action:value}));}

test("game spectators see public questions but no player's answer or trap word",async(context)=>{const running=await launch();const streams=[];context.after(()=>running.server.listening&&close(running,streams));const host=await create(running);streams.push(await events(running.base,host));const guest=(await post(running.base,"/api/join",{roomCode:host.roomCode,clientId:"p2",name:"二号",intent:"play"})).payload;streams.push(await events(running.base,guest));const full=(await post(running.base,"/api/join",{roomCode:host.roomCode,clientId:"full",name:"满房",intent:"play"})).payload;assert.equal(full.autoSpectated,true);assert.equal((await action(running,host,"start",{type:"start"})).response.status,200);const watcher=(await post(running.base,"/api/join",{roomCode:host.roomCode,clientId:"late",name:"晚到",intent:"play"})).payload;assert.equal(watcher.assignmentReason,"game_in_progress");assert.ok(watcher.view.words.every((item)=>item.word===null&&item.trapWord===null));assert.equal((await action(running,host,"question",{type:"question",text:"我是动物吗？"})).response.status,200);const observed=(await post(running.base,"/api/join",{roomCode:host.roomCode,clientId:watcher.clientId,resumeToken:watcher.resumeToken})).payload.view;assert.equal(observed.currentQuestion.text,"我是动物吗？");assert.ok(observed.words.every((item)=>item.word===null&&item.trapWord===null));const forged=await action(running,watcher,"answer",{type:"answer",answer:"yes"});assert.equal(forged.response.status,403);assert.equal(forged.payload.code,"spectator_cannot_act");});

test("game lobby role competition is atomic and collecting words locks seats",async(context)=>{const running=await launch();context.after(()=>running.server.listening&&close(running));const host=await create(running);const observers=[];for(const id of["a","b"])observers.push((await post(running.base,"/api/join",{roomCode:host.roomCode,clientId:id,name:id,intent:"spectate"})).payload);const results=await Promise.all(observers.map((observer)=>post(running.base,"/api/seat",auth(observer,{intent:"play"}))));assert.deepEqual(results.map(({response})=>response.status).sort(),[200,409]);const winner=observers[results.findIndex(({response})=>response.status===200)];await action(running,host,"configure",{type:"configure",gameMode:"playerWords",playerWordMode:"single",wordExtraMode:"none"});const hostStream=await events(running.base,host);const winnerStream=await events(running.base,winner);context.after(()=>{hostStream.destroy();winnerStream.destroy();});await action(running,host,"start",{type:"start"});const locked=await post(running.base,"/api/seat",auth(winner,{intent:"spectate"}));assert.equal(locked.response.status,409);assert.equal(locked.payload.code,"seat_change_unavailable");});

test("game SQLite restart preserves spectator identity and room setting",async(context)=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),"tablegame-game-spectator-"));let running=null;context.after(async()=>{if(running?.server.listening)await close(running);fs.rmSync(directory,{recursive:true,force:true});});const filename=path.join(directory,"game.sqlite");running=await launch({roomStore:createSqliteRoomStore({filename})});const host=await create(running);const watcher=(await post(running.base,"/api/join",{roomCode:host.roomCode,clientId:"watch",name:"旁观",intent:"spectate"})).payload;await post(running.base,"/api/room-settings",{roomCode:host.roomCode,hostId:host.clientId,resumeToken:host.resumeToken,allowSpectators:false});await close(running);running=await launch({roomStore:createSqliteRoomStore({filename})});const resumed=(await post(running.base,"/api/join",{roomCode:host.roomCode,clientId:watcher.clientId,resumeToken:watcher.resumeToken})).payload;assert.equal(resumed.memberRole,"spectator");assert.equal(resumed.view.allowSpectators,false);assert.ok(resumed.view.words.every((item)=>item.word===null&&item.trapWord===null));});

test("game page consumes shared spectator UI and renders read-only guidance",()=>{const html=fs.readFileSync(path.join(__dirname,"index.html"),"utf8");const script=fs.readFileSync(path.join(__dirname,"app.js"),"utf8");assert.match(html,/name="joinIntent" value="spectate"/);assert.match(html,/shared\/styles\/spectator\.css/);assert.match(html,/id="roomRoleBanner"/);assert.match(html,/id="spectatorList"/);assert.match(script,/createSpectatorUi/);assert.match(script,/答案对旁观者隐藏/);assert.match(script,/不能提交词语或参与问答/);assert.match(script,/spectator-action-note/);});
