"use strict";

import {
  bindRoomCodeInput,cleanPlayerName,createAuthoritativeRoomClient,createCountdown,
  createSessionStore,escapeHtml,renderConnectionStatus,renderCountdown,setHidden,setModeVisibility
} from "/shared/client/index.js";
import {ACTION_SECONDS,POWER_NAMES} from "./rules.mjs";

const PROTOCOL_VERSION=3;
const $=(id)=>document.getElementById(id);
const ids=["connectionStatus","setupPanel","roomPanel","hostModeButton","guestModeButton","hostSetup","guestSetup","hostNameInput","guestNameInput","playerCountSelect","createRoomButton","joinRoomButton","roomCodeInput","roomCodeDisplay","hostTools","roomPlayerCountSelect","startGameButton","endGameButton","scoreboard","notice","roundNumber","phaseLabel","deckCount","discardCount","discardPile","drawPile","pendingWrap","pendingCard","caboBanner","players","actionTitle","selectionHint","actionArea","timerText","timerBar","resultPanel","roundResults","logList","toggleLogButton"];
const E=Object.fromEntries(ids.map((id)=>[id,$(id)]));
let mode="host",view=null;
let selected=[];
const sessions=createSessionStore({gameId:"cabo"});
const countdown=createCountdown({onTick(value){renderCountdown({textElement:E.timerText,barElement:E.timerBar},value);}});
const room=createAuthoritativeRoomClient({protocolVersion:PROTOCOL_VERSION,sessionStore:sessions,onStatus(status){renderConnectionStatus(E.connectionStatus,status,room.snapshot().roomCode);},handlers:{onView(next){view=next;selected=selected.filter((key)=>findSlot(key));enterRoom();render();},onKicked(){alert("你已被房主移出房间。");location.reload();}}});

function selectMode(next){mode=next;setModeVisibility(mode,{hostSetup:E.hostSetup,guestSetup:E.guestSetup,hostTools:E.hostTools,hostButton:E.hostModeButton,guestButton:E.guestModeButton});}
function enterRoom(){setHidden(E.setupPanel,true);setHidden(E.roomPanel,false);E.roomCodeDisplay.textContent=room.snapshot().roomCode;}
function submit(action){return Promise.resolve(room.submitAction(action)).catch((error)=>{E.connectionStatus.textContent=`操作失败：${error.message}`;alert(error.message);});}
async function createGameRoom(){E.createRoomButton.disabled=true;try{await room.createRoom({name:cleanPlayerName(E.hostNameInput.value,"房主"),capacity:Number(E.playerCountSelect.value)});}catch(error){alert(`创建失败：${error.message}\n请确认已通过 node game13/signal-server.js 启动服务。`);}finally{E.createRoomButton.disabled=false;}}
async function joinGameRoom(){E.joinRoomButton.disabled=true;try{await room.joinRoom({code:E.roomCodeInput.value,name:cleanPlayerName(E.guestNameInput.value,"玩家")});}catch(error){alert(`加入失败：${error.message}`);}finally{E.joinRoomButton.disabled=false;}}
async function kickPlayer(playerId){const player=view.players.find((item)=>item.id===playerId);if(!player||player.isHost||!confirm(`确定移出 ${player.name} 吗？进行中的牌局会返回大厅。`))return;try{await room.kick(playerId);}catch(error){alert(error.message);}}
const keyFor=(playerId,slotId)=>`${playerId}:${slotId}`;
function findSlot(key){const [playerId,slotId]=key.split(":");const player=view?.players.find((item)=>item.id===playerId);const slot=player?.slots.find((item)=>item.slotId===slotId);return player&&slot?{player,slot}:null;}
function toggleSlot(playerId,slotId){const key=keyFor(playerId,slotId);selected=selected.includes(key)?selected.filter((item)=>item!==key):[...selected,key];render();}
function powerShort(value){return value===7||value===8?"PEEK":value===9||value===10?"SPY":value===11||value===12?"SWAP":"";}
function cardHtml(slot,ownerId){const shown=slot.value!==null;const classes=["card","slot-button",shown?"faceup":"back",shown&&powerShort(slot.value)?"power":"",selected.includes(keyFor(ownerId,slot.slotId))?"selected":"",slot.temporary?"temporary":""].filter(Boolean).join(" ");return `<button class="${classes}" data-owner="${escapeHtml(ownerId)}" data-slot="${escapeHtml(slot.slotId)}" data-power="${shown?powerShort(slot.value):""}">${shown?`<span>${slot.value}</span>`:"<span>CABO</span>"}</button>`;}
function looseCardHtml(card){if(!card)return '<div class="card pile-card empty">空</div>';const label=powerShort(card.value);return `<div class="card faceup ${label?"power":""}" data-power="${label}"><span>${card.value}</span></div>`;}
function seatForPlayer(player,index){
  if(player.id===view.selfId)return "self";
  const selfIndex=view.players.findIndex((item)=>item.id===view.selfId);
  const offset=(index-selfIndex+view.players.length)%view.players.length;
  if(view.players.length===2)return "top";
  if(view.players.length===3)return offset===1?"left":"right";
  return {1:"left",2:"top",3:"right"}[offset]||"top";
}
function renderPlayers(){E.players.innerHTML=view.players.map((player,index)=>`<article class="player seat-${seatForPlayer(player,index)} ${player.id===view.selfId?"self":""} ${player.id===view.currentPlayerId&&!["lobby","roundEnd","ended"].includes(view.phase)?"current":""}"><div class="player-head"><div><b>${escapeHtml(player.name)}</b> ${player.id===view.selfId?"· 你":""}<div class="player-meta">${player.isHost?"房主 · ":""}${player.connected?"在线":"离线"} · ${player.slots.length}张</div></div>${view.permissions.canKick&&!player.isHost?`<button class="kick" data-kick="${escapeHtml(player.id)}">移出</button>`:""}</div><div class="slots">${player.slots.map((slot)=>cardHtml(slot,player.id)).join("")}</div></article>`).join("");E.players.querySelectorAll("[data-slot]").forEach((button)=>button.addEventListener("click",()=>toggleSlot(button.dataset.owner,button.dataset.slot)));E.players.querySelectorAll("[data-kick]").forEach((button)=>button.addEventListener("click",()=>kickPlayer(button.dataset.kick)));}
function addButton(text,action,className=""){const button=document.createElement("button");button.textContent=text;button.className=className;button.addEventListener("click",()=>{selected=[];submit(action);});E.actionArea.append(button);}
function selectedParts(){return selected.map(findSlot).filter(Boolean);}
function renderActions(){E.actionArea.innerHTML="";E.selectionHint.textContent="";const me=view.players.find((player)=>player.id===view.selfId);const chosen=selectedParts();
  if(view.permissions.canInitialPeek){E.actionTitle.textContent="选择任意两张自己的牌";E.selectionHint.textContent=`已选择 ${chosen.filter((item)=>item.player.id===view.selfId).length}/2 张，确认后等待其他玩家。`;const own=chosen.filter((item)=>item.player.id===view.selfId);if(own.length===2)addButton("确认查看这两张",{type:"initialPeek",slotIds:own.map((item)=>item.slot.slotId)},"primary");return;}
  if(view.phase==="initialPeek"||view.phase==="initialReveal"){E.actionTitle.textContent=view.phase==="initialReveal"?"记住你查看的两张牌":"等待其他玩家选择初始牌";E.selectionHint.textContent="带红色光圈的牌只对你显示；倒计时结束后会重新盖住。";return;}
  if(view.permissions.canCloseReveal){E.actionTitle.textContent="记住这张牌";E.selectionHint.textContent="这是仅发送给你的临时私密视图。";addButton("提前盖回并结束回合",{type:"closeReveal"},"primary");return;}
  if(view.permissions.canDraw){E.actionTitle.textContent="轮到你行动";addButton("从牌库抽一张",{type:"drawDeck"},"primary");if(view.discardTop)addButton(`拿取弃牌 ${view.discardTop.value}`,{type:"drawDiscard"});if(view.permissions.canCallCabo)addButton("宣布 CABO",{type:"callCabo"},"cabo");return;}
  if(view.permissions.canPlaceFailedExchange){E.actionTitle.textContent="多牌匹配失败";E.selectionHint.textContent=`所选牌已经公开。请决定把抽到的 ${view.pendingCard.value} 放在手牌最左侧还是最右侧。`;addButton("放在最左侧",{type:"placeFailedExchange",end:"left"},"primary");addButton("放在最右侧",{type:"placeFailedExchange",end:"right"});return;}
  if(view.permissions.canExchange){E.actionTitle.textContent=`处理抽到的 ${view.pendingCard.value}`;const own=chosen.filter((item)=>item.player.id===view.selfId);E.selectionHint.textContent="选择自己的一张牌替换；也可以选择多张你认为数值相同的牌。";if(own.length===1)addButton("确认替换所选牌",{type:"exchange",slotIds:own.map((item)=>item.slot.slotId)},"primary");if(own.length>1)addButton(`确认尝试匹配 ${own.length} 张`,{type:"exchange",slotIds:own.map((item)=>item.slot.slotId)},"primary");if(view.permissions.canDiscard)addButton("直接弃掉，不发动能力",{type:"discardDrawn"});
    if(view.permissions.canUsePower){const power=view.pendingCard.power;if(power==="peek"){const ownBack=own.filter((item)=>!item.slot.faceUp);if(ownBack.length===1)addButton("发动PEEK查看所选牌",{type:"usePower",slotId:ownBack[0].slot.slotId},"power-action");E.selectionHint.textContent+=" PEEK需要选择自己一张背面牌。";}else if(power==="spy"){const targets=chosen.filter((item)=>item.player.id!==view.selfId&&!item.slot.faceUp);if(targets.length===1)addButton("发动SPY查看所选对手牌",{type:"usePower",targetPlayerId:targets[0].player.id,slotId:targets[0].slot.slotId},"power-action");E.selectionHint.textContent+=" SPY需要选择对手一张背面牌。";}else{const ownOne=own.length===1?own[0]:null;const other=chosen.filter((item)=>item.player.id!==view.selfId);if(ownOne&&other.length===1)addButton("发动SWAP交换两张牌",{type:"usePower",ownSlotId:ownOne.slot.slotId,targetPlayerId:other[0].player.id,targetSlotId:other[0].slot.slotId},"power-action");E.selectionHint.textContent+=" SWAP需要选择自己和对手各一张牌。";}}
    return;}
  if(view.phase==="roundEnd"){E.actionTitle.textContent="本轮已经结算";return;}if(view.phase==="ended"){E.actionTitle.textContent="整局游戏结束";return;}E.actionTitle.textContent=view.currentPlayerId?`等待 ${view.players.find((player)=>player.id===view.currentPlayerId)?.name} 行动`:"等待房主开始";
}
function renderScore(){E.scoreboard.innerHTML=view.players.map((player)=>`<div class="score-row"><span>${escapeHtml(player.name)}${player.resetUsed?" <small>已用100→50</small>":""}</span><b>${player.score}</b></div>`).join("");}
function renderResult(){const visible=view.roundResult.length>0;setHidden(E.resultPanel,!visible);if(!visible)return;E.roundResults.innerHTML=view.roundResult.map((item)=>{const player=view.players.find((entry)=>entry.id===item.playerId);const reason={caboSuccess:"CABO成功",caboPenalty:"CABO失败+10",kamikaze:"Kamikaze",kamikazePenalty:"Kamikaze惩罚",cards:"牌面"}[item.reason];return `<div class="result-row"><b>${escapeHtml(player?.name||"玩家")}</b><span>${reason}：+${item.score}${item.resetApplied?"，总分重置为50":""}</span><strong>累计 ${item.totalScore}</strong></div>`;}).join("");}
function phaseText(){return {lobby:"大厅",initialPeek:"选择初始牌",initialReveal:"私密记忆",turn:"行动阶段",drawn:"处理抽牌",failedExchange:"放置新增牌",reveal:"私密查看",roundEnd:"本轮结束",ended:"游戏结束"}[view.phase]||view.phase;}
function render(){if(!view)return;const current=view.players.find((player)=>player.id===view.currentPlayerId);setHidden(E.hostTools,!view.permissions.canManage);setHidden(E.startGameButton,!view.permissions.canStart);setHidden(E.endGameButton,!view.permissions.canEnd);E.startGameButton.textContent=view.phase==="roundEnd"?"开始下一轮":"开始游戏";E.startGameButton.disabled=(view.phase==="lobby"&&view.players.length!==view.capacity)||view.players.some((player)=>!player.connected);E.roomPlayerCountSelect.value=String(view.capacity);E.roomPlayerCountSelect.disabled=!view.permissions.canSetCapacity;E.roomCodeDisplay.textContent=room.snapshot().roomCode;E.roundNumber.textContent=view.round;E.phaseLabel.textContent=phaseText();E.deckCount.textContent=view.deckCount;E.discardCount.textContent=view.discardCount;E.discardPile.className=view.discardTop?"card pile-card faceup":"card pile-card empty";E.discardPile.innerHTML=view.discardTop?`<span>${view.discardTop.value}</span>`:"空";E.discardPile.dataset.power=view.discardTop?powerShort(view.discardTop.value):"";E.discardPile.classList.toggle("power",Boolean(E.discardPile.dataset.power));setHidden(E.pendingWrap,!view.pendingCard);if(view.pendingCard)E.pendingCard.innerHTML=looseCardHtml(view.pendingCard);setHidden(E.caboBanner,!view.cabo);if(view.cabo)E.caboBanner.textContent=`${view.players.find((player)=>player.id===view.cabo.callerId)?.name} 已宣布 CABO · 最终回合剩余 ${view.cabo.remainingIds.length} 人`;renderPlayers();renderScore();renderActions();renderResult();E.notice.textContent=view.phase==="lobby"?`等待玩家加入：${view.players.length}/${view.capacity}`:view.phase==="ended"?`胜者：${view.winnerIds.map((id)=>view.players.find((player)=>player.id===id)?.name).join("、")}`:current?`当前行动：${current.name}`:"牌局已结算";E.drawPile.disabled=!view.permissions.canDraw;E.drawPile.onclick=view.permissions.canDraw?()=>submit({type:"drawDeck"}):null;E.logList.innerHTML=view.logs.map((entry)=>`<div class="log-item">${escapeHtml(entry.text)}</div>`).join("");if(view.deadline)countdown.start(view.deadline,Math.max(ACTION_SECONDS*1000,view.deadline-Date.now()));else{countdown.stop();E.timerText.textContent="--";E.timerBar.style.width="0";}}
function endGame(){if(confirm("确定结束当前游戏并清空牌局进度吗？"))submit({type:"end"});}
async function init(){bindRoomCodeInput(E.roomCodeInput);E.hostModeButton.addEventListener("click",()=>selectMode("host"));E.guestModeButton.addEventListener("click",()=>selectMode("guest"));E.createRoomButton.addEventListener("click",createGameRoom);E.joinRoomButton.addEventListener("click",joinGameRoom);E.roomPlayerCountSelect.addEventListener("change",()=>submit({type:"setCapacity",capacity:Number(E.roomPlayerCountSelect.value)}));E.startGameButton.addEventListener("click",()=>submit({type:"start"}));E.endGameButton.addEventListener("click",endGame);E.toggleLogButton.addEventListener("click",()=>{const collapsed=E.logList.classList.toggle("collapsed");E.toggleLogButton.textContent=collapsed?"展开":"收起";});selectMode("host");try{await room.checkServer();}catch{/* create/join will show details */}}
init();
