"use strict";

import { bindRoomCodeInput, cleanPlayerName, createAuthoritativeRoomClient, createSessionStore, escapeHtml, renderConnectionStatus, setHidden, setModeVisibility } from "/shared/client/index.js";

const Engine=window.Engine, PROTOCOL_VERSION=3, COLORS=Engine.COLORS, TIER_KEYS=["stage3","stage2","stage1"];
const BALL_FILES={red:"red.png",blue:"blue.png",black:"black.png",pink:"pink.png",yellow:"yellow.png",purple:"master.png"};
const BALL_NAMES={red:"精灵球",blue:"超级球",black:"高级球",pink:"治愈球",yellow:"先机球",purple:"大师球"};
const $=(id)=>document.getElementById(id);
const E=Object.fromEntries(["connectionStatus","setupPanel","roomPanel","hostModeButton","guestModeButton","hostSetup","guestSetup","hostNameInput","guestNameInput","playerCountSelect","createRoomButton","joinRoomButton","roomCodeInput","roomCodeDisplay","hostTools","roomPlayerCountSelect","startGameButton","endGameButton","playerBadge","players","logList","toggleLogButton","notice","tokens","rareMarket","legendMarket","rareCount","legendCount","markets","actionTitle","phaseBadge","selectionSummary","actionArea","myScore","myResources","myPokemon","myReserved","reserveCount","trainerInspector","trainerInspectorTitle","trainerInspectorContent","closeTrainerInspectorButton"].map((id)=>[id,$(id)]));
let mode="host",view=null,cards=[],byId={},selection=[],selectedCardId=null,inspectedPlayerId=null;

const sessions=createSessionStore({gameId:"pokemon-splendor"});
const room=createAuthoritativeRoomClient({protocolVersion:PROTOCOL_VERSION,sessionStore:sessions,
  onStatus(status){renderConnectionStatus(E.connectionStatus,status,room.snapshot().roomCode);},
  handlers:{onView(nextView){view=nextView;enterRoom();render();},onKicked(){alert("你已被房主移出房间。");location.reload();}}
});
const roomInfo=()=>room.snapshot();
const currentView=()=>view;
const isHost=()=>roomInfo().role==="host";
function enterRoom(){setHidden(E.setupPanel,true);setHidden(E.roomPanel,false);setHidden(E.hostTools,!isHost());E.roomCodeDisplay.textContent=roomInfo().roomCode;}
function submit(action){selection=[];selectedCardId=null;return room.submitAction(action).catch((error)=>alert(`操作失败：${error.message}`));}

async function createGameRoom(){try{const name=cleanPlayerName(E.hostNameInput.value,"房主");await room.createRoom({name,capacity:Number(E.playerCountSelect.value)});}catch(error){alert(`创建失败：${error.message}\n请运行 node game8/signal-server.js`);}}
async function joinGameRoom(){try{await room.joinRoom({code:E.roomCodeInput.value,name:E.guestNameInput.value});E.connectionStatus.textContent="已连接，等待房主同步";}catch(error){alert(`加入失败：${error.message}`);}}
function changeCapacity(){if(!view)return;const n=Number(E.roomPlayerCountSelect.value);if(n<view.players.length){E.roomPlayerCountSelect.value=view.capacity;return alert("人数不能少于已加入玩家。");}submit({type:"setCapacity",capacity:n});}
function startGame(){submit({type:"start"});}
function endGame(){if(!view)return;if(view.phase==="ended")return submit({type:"restart"});if(confirm("确定结束本局并返回大厅吗？"))submit({type:"end"});}
function kickPlayer(playerId){if(confirm("确定移出这位训练家吗？"))room.kick(playerId).catch((error)=>alert(`移出失败：${error.message}`));}

const card=(id)=>typeof id==="string"?byId[id]:null;
const orbHtml=(color,n)=>`<span class="orb ${color}"><img src="${BALL_FILES[color]}" alt="${BALL_NAMES[color]}"><b>${n}</b></span>`;
function cardHtml(value,ctx="market"){
  if(!value)return '<div class="placeholder">牌位为空</div>';
  if(typeof value==="object"&&value.hidden)return '<article class="poke-card"><div class="art">?</div><div class="name">秘密保留卡</div></article>';
  const c=typeof value==="string"?card(value):value;if(!c)return"";
  const costs=Engine.ALL_TOKENS.filter((x)=>c.cost[x]>0).map((x)=>orbHtml(x,c.cost[x])).join("")||"免费";
  const selected=selectedCardId===c.id;
  const canReserve=ctx!=="reserved"&&["stage1","stage2","stage3"].includes(c.tier);
  const quickActions=selected?`<div class="card-quick-actions"><button class="primary" data-card-action="capture" data-card-id="${c.id}">捕捉</button>${canReserve?`<button data-card-action="reserve" data-card-id="${c.id}">保留</button>`:""}</div>`:"";
  return `<article class="poke-card ${selected?"selected":""}" data-card="${c.id}" data-context="${ctx}" style="--card:${{red:"#ffd7d9",black:"#d9dbea",yellow:"#fff2ad",pink:"#ffd9ec",blue:"#d7e8ff"}[c.bonus]}">${quickActions}<img class="card-face" src="${escapeHtml(c.img)}" alt="${escapeHtml(c.name)}"><div class="name"><span>${escapeHtml(c.name)}</span><span class="points">🏆${c.vp}</span></div><div class="cost">${costs}</div>${c.evolvesTo?`<div class="evo">可进化为 ${escapeHtml(c.evolvesTo)} · ${BALL_NAMES[c.evoCost.color]}×${c.evoCost.count}</div>`:""}</article>`;
}
function ownedPokemonHtml(id,g,player){const c=card(id);if(!c)return"";const bonusColor=Engine.effBonusColor(g,player,id),bonusCount=c.bonusCount||1;const bonus=bonusColor?`<span class="owned-bonus"><img src="${BALL_FILES[bonusColor]}" alt="${BALL_NAMES[bonusColor]}"><span>${BALL_NAMES[bonusColor]} ×${bonusCount}</span></span>`:'<span class="owned-bonus none">无永久奖励</span>';const evolution=c.evolvesTo&&c.evoCost?`可进化为 <b>${escapeHtml(c.evolvesTo)}</b><span class="evolution-cost"><img src="${BALL_FILES[c.evoCost.color]}" alt="${BALL_NAMES[c.evoCost.color]}">需拥有${BALL_NAMES[c.evoCost.color]}奖励 ×${c.evoCost.count}</span>`:"最终形态";return `<article class="owned-pokemon"><div class="owned-pokemon-main"><strong>${escapeHtml(c.name)}</strong><div class="owned-pokemon-stats">${bonus}<span class="owned-score">🏆 ${c.vp}</span></div></div><div class="owned-evolution">${evolution}</div></article>`;}
function reservedPokemonHtml(id,readonly=false){const c=card(id);if(!c)return"";const selected=!readonly&&selectedCardId===c.id;const bonusCount=c.bonusCount||1;const bonus=COLORS.includes(c.bonus)?`<span class="owned-bonus"><img src="${BALL_FILES[c.bonus]}" alt="${BALL_NAMES[c.bonus]}"><span>${BALL_NAMES[c.bonus]} ×${bonusCount}</span></span>`:'<span class="owned-bonus none">无永久奖励</span>';const costs=Engine.ALL_TOKENS.filter((color)=>c.cost[color]>0).map((color)=>`<span class="reserved-cost-item"><img src="${BALL_FILES[color]}" alt="${BALL_NAMES[color]}"><b>×${c.cost[color]}</b></span>`).join("")||'<span class="reserved-free">免费</span>';const evolution=c.evolvesTo&&c.evoCost?`可进化为 <b>${escapeHtml(c.evolvesTo)}</b><span class="evolution-cost"><img src="${BALL_FILES[c.evoCost.color]}" alt="${BALL_NAMES[c.evoCost.color]}">需拥有${BALL_NAMES[c.evoCost.color]}奖励 ×${c.evoCost.count}</span>`:"最终形态";const quickAction=selected?`<div class="card-quick-actions"><button class="primary" data-card-action="capture" data-card-id="${c.id}">捕捉</button></div>`:"";const attributes=readonly?'':`data-card="${c.id}" data-context="reserved"`;return `<article class="reserved-pokemon ${readonly?"readonly":""} ${selected?"selected":""}" ${attributes}>${quickAction}<div class="owned-pokemon-main"><strong>${escapeHtml(c.name)}</strong><div class="owned-pokemon-stats">${bonus}<span class="owned-score">🏆 ${c.vp}</span></div></div><div class="reserved-cost"><span>捕捉费用</span><div>${costs}</div></div><div class="owned-evolution">${evolution}</div></article>`;}
function secretReserveHtml(value){return `<article class="secret-reserve"><div class="secret-reserve-mark">?</div><div><strong>秘密保留卡</strong><span>${escapeHtml(Engine.zhTier(value?.tier||"未知"))} · 牌面仅持有者可见</span></div></article>`;}
const playerStats=(g,p)=>({score:Engine.scoreOf(g,p),bonuses:Engine.bonuses(g,p),tokens:Engine.tokenTotal(p)});
function closeTrainerInspector(){inspectedPlayerId=null;setHidden(E.trainerInspector,true);}
function inspectTrainer(playerId){inspectedPlayerId=playerId;render();}
function renderTrainerInspector(v,g,seat){if(!g||!inspectedPlayerId){setHidden(E.trainerInspector,true);return;}const index=v.players.findIndex((player)=>player.id===inspectedPlayerId);if(index<0||index===seat){closeTrainerInspector();return;}const rp=v.players[index],gp=g.players[index],stats=playerStats(g,gp);E.trainerInspectorTitle.textContent=`${rp.name} 的训练家板块`;E.trainerInspectorContent.innerHTML=`<div class="inspector-meta"><span>🏆 ${stats.score} 奖杯</span><span>${rp.connected?"在线":"离线"}</span><span>${g.turn===index&&v.phase==="playing"?"当前行动":"等待行动"}</span></div><section class="inspector-section"><h3>持有的精灵球</h3><div class="inspector-resources">${Engine.ALL_TOKENS.map((color)=>orbHtml(color,gp.tokens[color])).join("")}</div></section><section class="inspector-section"><h3>永久奖励</h3><div class="inspector-resources">${COLORS.map((color)=>orbHtml(color,stats.bonuses[color])).join("")}</div></section><section class="inspector-section"><div class="inspector-section-head"><h3>已捕捉的宝可梦</h3><span>${gp.board.length} 张 · 已进化 ${gp.buried.length} 张</span></div><div class="owned-pokemon-list">${gp.board.map((id)=>ownedPokemonHtml(id,g,gp)).join("")||'<div class="placeholder compact">还没有捕捉宝可梦</div>'}</div></section><section class="inspector-section"><div class="inspector-section-head"><h3>保留区</h3><span>${gp.reserve.length} / 3</span></div><div class="reserved-pokemon-list">${gp.reserve.map((value)=>typeof value==="string"?reservedPokemonHtml(value,true):secretReserveHtml(value)).join("")||'<div class="placeholder compact">没有保留卡</div>'}</div></section>`;setHidden(E.trainerInspector,false);}
function render(){
  const v=currentView();if(!v)return;const seat=v.players.findIndex((p)=>p.id===v.viewerId),g=v.game;
  // 网络视图会删除静态数据库，客户端用本地同版本数据重新挂载，只用于计算与渲染。
  if(g&&!g.byId){g.byId=byId;g.cardDB=cards;}
  const me=g?.players[seat],turn=g?.players[g.turn],myTurn=v.phase==="playing"&&g.turn===seat;
  const canStart=v.permissions?.canStart&&v.players.length===v.capacity&&v.players.every((p)=>p.connected);E.roomCodeDisplay.textContent=roomInfo().roomCode;setHidden(E.hostTools,!isHost());E.roomPlayerCountSelect.value=v.capacity;E.roomPlayerCountSelect.disabled=v.phase!=="lobby";E.playerBadge.textContent=`${v.players.length} / ${v.capacity}`;E.startGameButton.disabled=!canStart;setHidden(E.startGameButton,!v.permissions?.canStart);setHidden(E.endGameButton,!v.permissions?.canEnd&&!v.permissions?.canRestart);E.endGameButton.textContent=v.phase==="ended"?"返回大厅":"结束游戏";
  E.players.innerHTML=v.players.map((rp,i)=>{const gp=g?.players[i],s=gp?playerStats(g,gp):null;const kick=v.permissions?.canKick&&!rp.isHost?`<button class="small" data-kick="${escapeHtml(rp.id)}">移出</button>`:"";const name=g&&i!==seat?`<button class="trainer-inspect-button" data-inspect-player="${escapeHtml(rp.id)}">${escapeHtml(rp.name)} ${rp.isHost?"★":""} ${rp.connected?"":"(离线)"}</button>`:`<span>${escapeHtml(rp.name)} ${rp.isHost?"★":""} ${rp.connected?"":"(离线)"}</span>`;return `<div class="player ${g&&i===g.turn&&v.phase==="playing"?"turn":""} ${i===seat?"me":""}"><div class="player-top">${name}<span>🏆 ${s?.score||0}</span></div><div class="player-meta">${s?`奖励 ${COLORS.map((c)=>orbHtml(c,s.bonuses[c])).join(" ")} · 球 ${s.tokens} · 保留 ${gp.reserve.length} · 进化 ${gp.buried.length}`:"等待开始"}</div>${kick}</div>`;}).join("");E.players.querySelectorAll("[data-kick]").forEach((button)=>button.onclick=()=>kickPlayer(button.dataset.kick));E.players.querySelectorAll("[data-inspect-player]").forEach((button)=>button.onclick=()=>inspectTrainer(button.dataset.inspectPlayer));
  if(!g){renderLobby(v);return;}
  E.logList.innerHTML=[...g.log].reverse().map((x)=>`<div>${escapeHtml(x.msg)}</div>`).join("")||"<div>暂无记录</div>";
  E.tokens.innerHTML=Engine.ALL_TOKENS.map((c)=>`<button class="token ${c} ${selection.includes(c)?"selected":""}" data-token="${c}" ${!myTurn||g.acted||c==="purple"?"disabled":""}><b>${g.supply[c]}</b><span>${BALL_NAMES[c]}</span></button>`).join("");
  E.rareCount.textContent=`牌库 ${g.decks.rare.length}`;E.legendCount.textContent=`牌库 ${g.decks.legend.length}`;E.rareMarket.innerHTML=g.field.rare.map((id)=>cardHtml(id)).join("");E.legendMarket.innerHTML=g.field.legend.map((id)=>cardHtml(id)).join("");
  E.markets.innerHTML=TIER_KEYS.map((tier)=>`<section class="market-row"><div class="deck" data-blind="${tier}"><b>${Engine.zhTier(tier)}</b><span>剩余 ${g.decks[tier].length}<br>点击暗中保留</span></div><div class="cards">${g.field[tier].map((id)=>cardHtml(id)).join("")}</div></section>`).join("");
  const ms=playerStats(g,me);E.myScore.innerHTML=`${ms.score} <small>奖杯</small>`;E.myResources.innerHTML=Engine.ALL_TOKENS.map((c)=>orbHtml(c,`${me.tokens[c]} + ${ms.bonuses[c]||0}`)).join("");E.myPokemon.innerHTML=me.board.map((id)=>ownedPokemonHtml(id,g,me)).join("")||'<div class="placeholder">还没有捕捉宝可梦</div>';E.reserveCount.textContent=`${me.reserve.length} / 3`;E.myReserved.innerHTML=me.reserve.map((id)=>reservedPokemonHtml(id)).join("")||'<div class="placeholder">没有保留卡</div>';
  renderActions(v,g,me,myTurn,turn);bindBoard(g,me,myTurn);renderTrainerInspector(v,g,seat);
}
function renderLobby(v){closeTrainerInspector();E.notice.textContent=`等待训练家加入（${v.players.length}/${v.capacity}）`;E.actionTitle.textContent="准备阶段";E.phaseBadge.textContent="大厅";E.tokens.innerHTML="";E.markets.innerHTML="";E.rareMarket.innerHTML="";E.legendMarket.innerHTML="";E.myPokemon.innerHTML="";E.myReserved.innerHTML="";E.myResources.innerHTML="";E.myScore.textContent="0";E.actionArea.innerHTML="";E.logList.innerHTML="<div>创建房间后等待所有训练家到齐。</div>";}
function renderActions(v,g,me,myTurn,turn){
  E.actionArea.innerHTML="";E.selectionSummary.textContent="";E.phaseBadge.textContent=v.phase==="ended"?"游戏结束":g.lastRound?"最后一轮":`第 ${g.round} 轮`;
  if(v.phase==="ended"){E.notice.textContent=`${g.players[g.winner].name} 获胜！`;E.actionTitle.textContent="挑战结束";return;}
  const ts=Engine.turnState(g);E.notice.textContent=myTurn?"轮到你行动":`等待 ${turn.name} 行动`;E.actionTitle.textContent=myTurn?"请选择操作":`当前训练家：${turn.name}`;if(!myTurn)return;
  if(ts.mustDiscard){E.actionTitle.textContent=`请归还 ${ts.mustDiscard} 个精灵球`;Engine.ALL_TOKENS.filter((c)=>me.tokens[c]>0).forEach((c)=>addBallButton(c,()=>submit({type:"discard",color:c})));return;}
  if(!g.acted){const need=Math.min(3,COLORS.filter((c)=>g.supply[c]>0).length);E.selectionSummary.textContent=selection.length?`已选择：${selection.map((c)=>BALL_NAMES[c]).join("、")}`:`选择 ${need} 种颜色，或同色两个`;addButton(`拿取 ${need} 种不同颜色`,()=>submit({type:"take",colors:selection}),selection.length!==need);if(selection.length===1&&g.supply[selection[0]]>=4)addButton(`拿取两个${BALL_NAMES[selection[0]]}`,()=>submit({type:"take",colors:[selection[0],selection[0]]}));return;}
  const hasEvolution=ts.evolutions.length>0||ts.megaEvolutions.length>0;E.actionTitle.textContent=hasEvolution?"选择进化或跳过":"结束当前回合";for(const opt of ts.evolutions)addButton(`进化：${card(opt.fromId).name} → ${card(opt.toId).name}`,()=>submit({type:"evolve",fromId:opt.fromId,toId:opt.toId}));addButton(hasEvolution?"跳过进化并结束回合":"结束回合",()=>submit({type:"endTurn"}));
}
function addButton(text,on,disabled=false){const b=document.createElement("button");b.textContent=text;b.disabled=disabled;b.onclick=on;E.actionArea.appendChild(b);}
function addBallButton(color,on){const b=document.createElement("button");b.className=`return-ball ${color}`;const img=document.createElement("img");img.src=BALL_FILES[color];img.alt="";img.setAttribute("aria-hidden","true");const label=document.createElement("span");label.textContent=`归还一个${BALL_NAMES[color]}`;b.append(img,label);b.onclick=on;E.actionArea.appendChild(b);}
function bindBoard(g,me,myTurn){
  E.tokens.querySelectorAll("[data-token]").forEach((b)=>b.onclick=()=>{const c=b.dataset.token;if(selection.includes(c))selection=selection.filter((x)=>x!==c);else if(selection.length<3)selection.push(c);render();});
  if(!myTurn||g.acted)return;
  document.querySelectorAll('[data-card][data-context]:not([data-context="mine"])').forEach((el)=>el.onclick=(event)=>{event.stopPropagation();selectedCardId=el.dataset.card;render();});
  document.querySelectorAll("[data-card-action]").forEach((button)=>button.onclick=(event)=>{event.stopPropagation();const id=button.dataset.cardId;if(button.dataset.cardAction==="capture")submit({type:"capture",cardId:id});else submit({type:"reserve",target:{fromField:id}});});
  document.querySelectorAll("[data-blind]").forEach((el)=>el.onclick=()=>{if(confirm(`暗中保留${Engine.zhTier(el.dataset.blind)}牌堆顶卡？`))submit({type:"reserve",target:{fromDeck:el.dataset.blind}});});
}

async function init(){const response=await fetch("./data/cards.json");if(!response.ok)throw new Error("卡牌数据库加载失败");cards=await response.json();byId=Object.fromEntries(cards.map((c)=>[c.id,c]));E.hostModeButton.onclick=()=>{mode="host";setModeVisibility(mode,{...E,hostButton:E.hostModeButton,guestButton:E.guestModeButton});};E.guestModeButton.onclick=()=>{mode="guest";setModeVisibility(mode,{...E,hostButton:E.hostModeButton,guestButton:E.guestModeButton});};E.createRoomButton.onclick=createGameRoom;E.joinRoomButton.onclick=joinGameRoom;bindRoomCodeInput(E.roomCodeInput);E.roomPlayerCountSelect.onchange=changeCapacity;E.startGameButton.onclick=startGame;E.endGameButton.onclick=endGame;E.toggleLogButton.onclick=()=>E.logList.classList.toggle("collapsed");E.closeTrainerInspectorButton.onclick=closeTrainerInspector;E.trainerInspector.onclick=(event)=>{if(event.target===E.trainerInspector)closeTrainerInspector();};document.addEventListener("keydown",(event)=>{if(event.key==="Escape"&&!E.trainerInspector.classList.contains("hidden"))closeTrainerInspector();});document.addEventListener("click",()=>{if(selectedCardId){selectedCardId=null;render();}});setModeVisibility(mode,{...E,hostButton:E.hostModeButton,guestButton:E.guestModeButton});room.checkServer().catch(()=>{});}
init().catch((error)=>{E.connectionStatus.textContent=error.message;console.error(error);});
