"use strict";
const COLORS = ["red", "black", "yellow", "pink", "blue"], NAMES = { red: "红球", black: "黑球", yellow: "黄球", pink: "粉球", blue: "蓝球", master: "大师球" }, ICONS = Object.fromEntries([...COLORS, "master"].map(color => [color, `<img class="mini-ball" src="${color}.png" alt="${color}">`]));
const RAW = {
  1: ["妙蛙种子|yellow|0|blue2,yellow1,black1", "小火龙|red|0|red1,pink1,black2", "杰尼龟|blue|0|blue1,yellow1,black2", "皮卡丘|pink|0|red1,blue1,pink1,black1", "绿毛虫|yellow|0|yellow2,pink1", "独角虫|black|0|yellow1,black2", "波波|pink|0|blue1,pink2", "小拉达|black|0|red1,black2", "烈雀|red|0|red2,pink1", "阿柏蛇|black|0|yellow2,black1", "穿山鼠|pink|0|red1,pink2", "尼多兰|blue|0|blue2,yellow1", "尼多朗|red|0|red2,black1", "皮皮|pink|0|blue1,pink2", "六尾|red|0|red2,yellow1", "胖丁|blue|0|blue2,pink1", "超音蝠|black|0|black2,pink1", "走路草|yellow|0|yellow2,blue1", "派拉斯|yellow|0|red1,yellow2", "地鼠|black|0|black2,red1"],
  2: ["妙蛙草|yellow|1|blue2,yellow3,black2|妙蛙种子|yellow3", "火恐龙|red|1|red3,pink2,black2|小火龙|red3", "卡咪龟|blue|1|blue3,yellow2,black2|杰尼龟|blue3", "雷丘|pink|2|red2,blue2,pink4|皮卡丘|pink4", "铁甲蛹|yellow|1|yellow4,pink2|绿毛虫|yellow4", "铁壳蛹|black|1|yellow2,black4|独角虫|black4", "比比鸟|pink|1|blue2,pink4|波波|pink4", "拉达|black|1|red2,black4|小拉达|black4", "阿柏怪|black|2|yellow3,black5|阿柏蛇|black4", "穿山王|pink|2|red3,pink5|穿山鼠|pink4", "尼多娜|blue|1|blue4,yellow2|尼多兰|blue4", "尼多力诺|red|1|red4,black2|尼多朗|red4", "九尾|red|2|red5,yellow3|六尾|red4", "大嘴蝠|black|2|black5,pink3|超音蝠|black4", "臭臭花|yellow|2|yellow5,blue3|走路草|yellow4", "派拉斯特|yellow|2|red3,yellow5|派拉斯|yellow4"],
  3: ["妙蛙花|yellow|4|blue3,yellow6,black3|妙蛙草|yellow5", "喷火龙|red|5|red7,pink3,black3|火恐龙|red5", "水箭龟|blue|5|blue7,yellow3,black3|卡咪龟|blue5", "巴大蝶|pink|3|yellow5,pink5|铁甲蛹|yellow5", "大针蜂|black|3|yellow5,black5|铁壳蛹|black5", "大比鸟|pink|4|blue4,pink7|比比鸟|pink5", "尼多后|blue|4|blue7,yellow4,black3|尼多娜|blue5", "尼多王|red|4|red7,pink3,black4|尼多力诺|red5", "霸王花|yellow|4|yellow7,blue4,red3|臭臭花|yellow5", "叉字蝠|black|4|black7,pink4,blue3|大嘴蝠|black5", "风速狗|red|4|red7,yellow3,pink3", "哥达鸭|blue|4|blue7,black3,yellow3"]
};
const SPECIAL = {
  rare: ["卡比兽|yellow+pink|3|master1,red3,blue3", "拉普拉斯|blue+black|3|master1,yellow3,pink3", "百变怪|red+blue|3|master1,pink3,black3", "伊布|pink+yellow|3|master1,red3,black3", "化石翼龙|black+red|3|master1,blue3,yellow3"],
  legend: ["急冻鸟|blue+pink|5|master1,blue4,pink4", "闪电鸟|pink+black|5|master1,pink4,black4", "火焰鸟|red+yellow|5|master1,red4,yellow4", "梦幻|blue+red|5|master1,blue4,red4", "超梦|black+pink|5|master1,black4,pink4"]
};
let mode = "host", selfId = "", roomCode = "", hostId = "", events = null, state = null, guestView = null, selection = [], selectedCard = null;
const $ = id => document.getElementById(id), E = { connectionStatus: $("connectionStatus"), setupPanel: $("setupPanel"), roomPanel: $("roomPanel"), hostModeButton: $("hostModeButton"), guestModeButton: $("guestModeButton"), hostSetup: $("hostSetup"), guestSetup: $("guestSetup"), hostNameInput: $("hostNameInput"), guestNameInput: $("guestNameInput"), playerCountSelect: $("playerCountSelect"), createRoomButton: $("createRoomButton"), joinRoomButton: $("joinRoomButton"), roomCodeInput: $("roomCodeInput"), roomCodeDisplay: $("roomCodeDisplay"), hostTools: $("hostTools"), roomPlayerCountSelect: $("roomPlayerCountSelect"), startGameButton: $("startGameButton"), endGameButton: $("endGameButton"), playerBadge: $("playerBadge"), players: $("players"), logList: $("logList"), toggleLogButton: $("toggleLogButton"), notice: $("notice"), tokens: $("tokens"), rareMarket: $("rareMarket"), legendMarket: $("legendMarket"), rareCount: $("rareCount"), legendCount: $("legendCount"), markets: $("markets"), actionTitle: $("actionTitle"), phaseBadge: $("phaseBadge"), selectionSummary: $("selectionSummary"), actionArea: $("actionArea"), myScore: $("myScore"), myResources: $("myResources"), myPokemon: $("myPokemon"), myReserved: $("myReserved"), reserveCount: $("reserveCount"), modal: $("modal"), modalTitle: $("modalTitle"), modalBody: $("modalBody"), modalActions: $("modalActions") };
const uid = p => `${p}_${Math.random().toString(36).slice(2, 10)}`, clean = (v, d) => String(v || "").trim().slice(0, 12) || d, esc = v => String(v ?? "").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[c]));
function parseCost(s) { return Object.fromEntries((s || "").split(",").filter(Boolean).map(x => [x.match(/[a-z]+/)[0], Number(x.match(/\d+/)[0])])) }
function parseCard(row, tier, kind = "normal") { const [name, bonus, points, cost, from, evo] = row.split("|"), mainColor = bonus.split("+")[0]; return { id: uid("card"), name, bonus: bonus.split("+"), points: Number(points), cost: parseCost(cost), tier, kind, evolvesFrom: from || null, evolutionCost: parseCost(evo), icon: `<img class="card-ball" src="${mainColor}.png" alt="${NAMES[mainColor]}">` } }
function shuffle(a) { for (let i = a.length - 1; i; i--) { const j = Math.floor(Math.random() * (i + 1));[a[i], a[j]] = [a[j], a[i]] } return a }
function freshDeck(rows, tier, kind) { return shuffle(rows.map(x => parseCard(x, tier, kind))) }
function emptyTokens() { return { red: 0, blue: 0, yellow: 0, pink: 0, black: 0, master: 0 } }
function player(id, name, host = false) { return { id, name, isHost: host, connected: true, tokens: emptyTokens(), pokemon: [], reserved: [], evolved: [] } }
async function post(path, data) { const r = await fetch(path, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); if (!r.ok) throw Error(await r.text()); return r.json() }
const signal = (to, payload) => post("/api/signal", { roomCode, from: selfId, to, payload });
function openEvents(id) { events?.close(); events = new EventSource(`/api/events?clientId=${encodeURIComponent(id)}`); events.addEventListener("signal", e => receive(JSON.parse(e.data))); events.onopen = () => E.connectionStatus.textContent = `已连接房间 ${roomCode}`; events.onerror = () => E.connectionStatus.textContent = "联机服务正在重连" }
function receive(m) { const p = m.payload; if (mode === "host" && p?.kind === "hello") return admit(m.from, p.name); if (mode === "host" && p?.kind === "action") return act(m.from, p.action); if (mode === "guest" && p?.kind === "view") { guestView = p.view; enter(); render() } if (mode === "guest" && p?.kind === "rejected") { events?.close(); alert(p.message) } }
function setMode(m) { mode = m; E.hostModeButton.classList.toggle("active", m === "host"); E.guestModeButton.classList.toggle("active", m === "guest"); E.hostSetup.classList.toggle("hidden", m !== "host"); E.guestSetup.classList.toggle("hidden", m !== "guest") }
function enter() { E.setupPanel.classList.add("hidden"); E.roomPanel.classList.remove("hidden"); E.hostTools.classList.toggle("hidden", mode !== "host"); E.roomCodeDisplay.textContent = roomCode }
async function createRoom() { selfId = uid("host"); state = { phase: "lobby", capacity: Number(E.playerCountSelect.value), players: [player(selfId, clean(E.hostNameInput.value, "房主"), true)], supply: emptyTokens(), decks: {}, market: {}, currentIndex: 0, startIndex: 0, round: 0, turnStage: "action", endTriggered: false, endAfterIndex: null, winners: [], logs: [] }; try { const r = await post("/api/rooms", { hostId: selfId }); roomCode = r.roomCode; E.roomPlayerCountSelect.value = state.capacity; openEvents(selfId); enter(); render() } catch (e) { alert(`创建失败：${e.message}\n请运行 node game8/signal-server.js`) } }
async function joinRoom() { roomCode = E.roomCodeInput.value.trim().toUpperCase(); if (!/^[A-Z0-9]{4}$/.test(roomCode)) return alert("请输入四位房间号。"); selfId = uid("guest"); try { const r = await post("/api/join", { roomCode, clientId: selfId, name: clean(E.guestNameInput.value, "训练家") }); hostId = r.hostId; openEvents(selfId); E.connectionStatus.textContent = "等待房主同步状态" } catch { alert("房间不存在或联机服务未启动。") } }
function admit(id, name) { const old = state.players.find(p => p.id === id); if (old) { old.connected = true; return sync() } if (state.phase !== "lobby") return signal(id, { kind: "rejected", message: "挑战已经开始。" }); if (state.players.length >= state.capacity) return signal(id, { kind: "rejected", message: "房间人数已满。" }); state.players.push(player(id, clean(name, "训练家"))); log(`${clean(name, "训练家")} 加入房间`); sync() }
function changeCapacity() { const n = Number(E.roomPlayerCountSelect.value); if (n < state.players.length) { alert("人数不能少于已加入玩家。"); return E.roomPlayerCountSelect.value = state.capacity } state.capacity = n; sync() }
function startGame() { if (state.players.length !== state.capacity) return alert(`需要 ${state.capacity} 位训练家到齐。`); state.decks = { 1: freshDeck(RAW[1], 1), 2: freshDeck(RAW[2], 2), 3: freshDeck(RAW[3], 3), rare: freshDeck(SPECIAL.rare, 4, "rare"), legend: freshDeck(SPECIAL.legend, 5, "legend") }; state.market = { 1: state.decks[1].splice(-4), 2: state.decks[2].splice(-4), 3: state.decks[3].splice(-4), rare: state.decks.rare.splice(-1), legend: state.decks.legend.splice(-1) }; const n = { 2: 4, 3: 5, 4: 7 }[state.capacity]; COLORS.forEach(c => state.supply[c] = n); state.supply.master = 5; state.players.forEach(p => { p.tokens = emptyTokens(); p.pokemon = []; p.reserved = []; p.evolved = [] }); state.phase = "playing"; state.currentIndex = 0; state.startIndex = 0; state.round = 1; state.turnStage = "action"; state.endTriggered = false; state.winners = []; state.logs = []; log("训练家挑战开始"); sync() }
function endGame() { if (!confirm("确定结束本局并返回大厅吗？")) return; state.phase = "lobby"; state.logs = []; sync() }
const current = () => state.players[state.currentIndex], tokenCount = p => Object.values(p.tokens).reduce((a, b) => a + b, 0), score = p => p.pokemon.reduce((s, c) => s + c.points, 0);
function bonuses(p) { const b = emptyTokens(); p.pokemon.forEach(c => c.bonus.forEach(x => b[x]++)); return b }
function log(text) { state.logs.unshift({ id: uid("log"), text }); state.logs = state.logs.slice(0, 80) }
function submit(action) { selection = []; selectedCard = null; if (mode === "host") act(selfId, action); else signal(hostId, { kind: "action", action }) }
function act(id, a) {
  if (state.phase !== "playing" || current().id !== id) return; const p = current(); if (state.turnStage === "discard") return discardAction(p, a); if (state.turnStage === "evolve") return evolveAction(p, a); if (state.turnStage !== "action") return;
  if (a.type === "takeDifferent") takeDifferent(p, a.colors); else if (a.type === "takeSame") takeSame(p, a.color); else if (a.type === "reserve") reserve(p, a); else if (a.type === "capture") capture(p, a); else return;
}
function takeDifferent(p, colors) { const available = COLORS.filter(c => state.supply[c] > 0), required = Math.min(3, available.length), chosen = [...new Set(colors || [])]; if (chosen.length !== required || chosen.some(c => !available.includes(c))) return; chosen.forEach(c => { state.supply[c]--; p.tokens[c]++ }); log(`${p.name} 拿取 ${chosen.map(c => NAMES[c]).join("、")}`); afterMain(p) }
function takeSame(p, c) { if (!COLORS.includes(c) || state.supply[c] < 4) return; state.supply[c] -= 2; p.tokens[c] += 2; log(`${p.name} 拿取两个${NAMES[c]}`); afterMain(p) }
function findMarket(kind, id) { const list = state.market[kind] || []; return { list, index: list.findIndex(c => c.id === id) } }
function refill(kind) { if (state.decks[kind]?.length) state.market[kind].push(state.decks[kind].pop()) }
function reserve(p, a) { if (p.reserved.length >= 3) return; let card; if (a.blind) { if (!["1", "2", "3"].includes(String(a.kind)) || !state.decks[a.kind].length) return; card = state.decks[a.kind].pop() } else { if (!["1", "2", "3"].includes(String(a.kind))) return; const f = findMarket(a.kind, a.cardId); if (f.index < 0) return; card = f.list.splice(f.index, 1)[0]; refill(a.kind) } p.reserved.push(card); if (state.supply.master > 0) { state.supply.master--; p.tokens.master++ } log(`${p.name} 保留了一只宝可梦${state.supply.master >= 0 ? "" : ""}`); afterMain(p) }
function locateCard(p, a) { if (a.source === "reserved") { const i = p.reserved.findIndex(c => c.id === a.cardId); return i < 0 ? null : { card: p.reserved[i], remove: () => p.reserved.splice(i, 1) } } const f = findMarket(a.kind, a.cardId); return f.index < 0 ? null : { card: f.list[f.index], remove: () => { f.list.splice(f.index, 1); refill(a.kind) } } }
function requiredPayment(p, card) { const b = bonuses(p), need = {}; for (const [c, n] of Object.entries(card.cost)) need[c] = Math.max(0, n - (b[c] || 0)); return need }
function capture(p, a) { const found = locateCard(p, a); if (!found) return; const need = requiredPayment(p, found.card), pay = a.payment || {}, mandatory = need.master || 0; let substitutes = 0; for (const c of COLORS) { const n = need[c] || 0, used = Math.max(0, Number(pay[c] || 0)); if (used > p.tokens[c] || used > n) return; substitutes += n - used } const m = Math.max(0, Number(pay.master || 0)); if (m !== mandatory + substitutes || m > p.tokens.master) return; for (const c of [...COLORS, "master"]) { const n = Math.max(0, Number(pay[c] || 0)); if (n > p.tokens[c]) return; p.tokens[c] -= n; state.supply[c] += n } found.remove(); p.pokemon.push(found.card); log(`${p.name} 捕捉了 ${found.card.name}，获得 ${found.card.points} 枚奖杯`); afterMain(p) }
function afterMain(p) { state.turnStage = tokenCount(p) > 10 ? "discard" : "evolve"; sync() }
function discardAction(p, a) { if (a.type !== "discard") return; const give = a.tokens || {}, total = Object.values(give).reduce((s, n) => s + Number(n || 0), 0); if (total !== tokenCount(p) - 10) return; for (const [c, n0] of Object.entries(give)) { const n = Number(n0); if (n < 0 || n > p.tokens[c]) return } for (const [c, n0] of Object.entries(give)) { const n = Number(n0); p.tokens[c] -= n; state.supply[c] += n } log(`${p.name} 归还了 ${total} 个精灵球`); state.turnStage = "evolve"; sync() }
function evolvable(p) { const b = bonuses(p), out = []; for (const [kind, list] of Object.entries(state.market)) for (const card of list) if (card.evolvesFrom && p.pokemon.some(x => x.name === card.evolvesFrom) && Object.entries(card.evolutionCost).every(([c, n]) => b[c] >= n)) out.push({ card, kind, source: "market" }); for (const card of p.reserved) if (card.evolvesFrom && p.pokemon.some(x => x.name === card.evolvesFrom) && Object.entries(card.evolutionCost).every(([c, n]) => b[c] >= n)) out.push({ card, source: "reserved" }); return out }
function evolveAction(p, a) { if (a.type === "skipEvolve") return finishTurn(); if (a.type !== "evolve") return; const option = evolvable(p).find(x => x.card.id === a.cardId && x.source === a.source); if (!option) return; const oldIndex = p.pokemon.findIndex(x => x.name === option.card.evolvesFrom), old = p.pokemon.splice(oldIndex, 1)[0]; if (option.source === "reserved") p.reserved.splice(p.reserved.findIndex(x => x.id === option.card.id), 1); else { const f = findMarket(option.kind, option.card.id); f.list.splice(f.index, 1); refill(option.kind) } p.evolved.push(old); p.pokemon.push(option.card); log(`${p.name} 将 ${old.name} 进化成 ${option.card.name}`); finishTurn() }
function finishTurn() { const p = current(); if (!state.endTriggered && score(p) >= 18) { state.endTriggered = true; state.endAfterIndex = (state.startIndex + state.players.length - 1) % state.players.length; log(`${p.name} 达到 18 分，当前轮为最后一轮`) } if (state.endTriggered && state.currentIndex === state.endAfterIndex) return finishGame(); state.currentIndex = (state.currentIndex + 1) % state.players.length; if (state.currentIndex === state.startIndex) state.round++; state.turnStage = "action"; sync() }
function finishGame() { state.phase = "ended"; const ranked = [...state.players].sort((a, b) => score(b) - score(a) || b.evolved.length - a.evolved.length || (b.pokemon.length + b.evolved.length) - (a.pokemon.length + a.evolved.length)); const best = ranked[0]; state.winners = ranked.filter(p => score(p) === score(best) && p.evolved.length === best.evolved.length && (p.pokemon.length + p.evolved.length) === (best.pokemon.length + best.evolved.length)).map(p => p.id); log(`${state.winners.map(id => state.players.find(p => p.id === id).name).join("、")} 赢得训练家挑战！`); sync() }
function buildView(viewer) { return { selfId: viewer, phase: state.phase, capacity: state.capacity, currentIndex: state.currentIndex, round: state.round, turnStage: state.turnStage, endTriggered: state.endTriggered, winners: state.winners, supply: state.supply, decks: Object.fromEntries(Object.entries(state.decks).map(([k, v]) => [k, v.length])), market: state.market, logs: state.logs, players: state.players.map(p => ({ ...p, reserved: p.id === viewer ? p.reserved : p.reserved.map(c => ({ id: c.id, hidden: true })), score: score(p), bonuses: bonuses(p) })) } }
const view = () => mode === "host" ? (state ? buildView(selfId) : null) : guestView;
function broadcast() { if (mode !== "host") return; state.players.filter(p => p.id !== selfId).forEach(p => signal(p.id, { kind: "view", view: buildView(p.id) }).catch(() => p.connected = false)) }
function sync() { render(); broadcast() }
function orbHtml(c, n) { return `<span class="orb ${c}"><img src="${c}.png" alt="${NAMES[c]}"><b>${n}</b></span>` }
function cardHtml(card, ctx = "market") { if (!card || card.hidden) return `<div class="poke-card"><div class="art">?</div><div class="name">秘密保留卡</div></div>`; return `<article class="poke-card" data-card="${card.id}" style="--card:${{ red: "#ffd7d9", black: "#d9dbea", yellow: "#fff2ad", pink: "#ffd9ec", blue: "#d7e8ff" }[card.bonus[0]]}"><div class="art">${card.icon}</div><div class="name"><span>${esc(card.name)}</span><span class="points">🏆${card.points}</span></div><div class="cost">${Object.entries(card.cost).map(([c, n]) => orbHtml(c, n)).join("") || "免费"}</div><div class="bonus">奖励 ${card.bonus.map(c => orbHtml(c, 1)).join("")}</div>${card.evolvesFrom ? `<div class="evo">${esc(card.evolvesFrom)} → ${Object.entries(card.evolutionCost).map(([c, n]) => `${NAMES[c]}×${n}`).join(" ")}</div>` : ""}</article>` }
function render() {
  const v = view(); if (!v) return; const me = v.players.find(p => p.id === v.selfId), turn = v.players[v.currentIndex], myTurn = v.phase === "playing" && turn?.id === v.selfId; E.roomCodeDisplay.textContent = roomCode; E.roomPlayerCountSelect.value = v.capacity; E.playerBadge.textContent = `${v.players.length} / ${v.capacity}`; E.startGameButton.disabled = v.phase !== "lobby"; E.players.innerHTML = v.players.map((p, i) => `<div class="player ${i === v.currentIndex && v.phase === "playing" ? "turn" : ""} ${p.id === v.selfId ? "me" : ""}"><div class="player-top"><span>${esc(p.name)} ${p.isHost ? "★" : ""}</span><span>🏆 ${p.score}</span></div><div class="player-meta">奖励 ${COLORS.map(c => `${ICONS[c]}${p.bonuses[c]}`).join(" ")} · 球 ${Object.values(p.tokens).reduce((a, b) => a + b, 0)} · 保留 ${p.reserved.length} · 进化 ${p.evolved.length}</div></div>`).join(""); E.logList.innerHTML = v.logs.map(x => `<div>${esc(x.text)}</div>`).join("") || "<div>暂无记录</div>";
  E.tokens.innerHTML = [...COLORS, "master"].map(c => `<button class="token ${c} ${selection.includes(c) ? "selected" : ""}" data-token="${c}" ${!myTurn || v.turnStage !== "action" || c === "master" ? "disabled" : ""}><b>${v.supply[c]}</b><span>${NAMES[c]}</span></button>`).join("");
  E.rareCount.textContent = `牌库 ${v.decks.rare || 0}`; E.legendCount.textContent = `牌库 ${v.decks.legend || 0}`; E.rareMarket.innerHTML = v.market?.rare?.map(c => cardHtml(c)).join("") || '<div class="placeholder">已捕捉完毕</div>'; E.legendMarket.innerHTML = v.market?.legend?.map(c => cardHtml(c)).join("") || '<div class="placeholder">已捕捉完毕</div>';
  E.markets.innerHTML = [3, 2, 1].map(t => `<section class="market-row"><div class="deck" data-blind="${t}"><b>等级 ${["", "Ⅰ", "Ⅱ", "Ⅲ"][t]}</b><span>剩余 ${v.decks[t] || 0}<br>点击暗中保留</span></div><div class="cards">${v.market?.[t]?.map(c => cardHtml(c)).join("") || '<div class="placeholder">牌库已空</div>'}</div></section>`).join("");
  E.myScore.innerHTML = `${me.score} <small>奖杯</small>`; E.myResources.innerHTML = [...COLORS, "master"].map(c => orbHtml(c, `${me.tokens[c]} + ${me.bonuses[c] || 0}`)).join(""); E.myPokemon.innerHTML = me.pokemon.map(c => cardHtml(c, "mine")).join("") || '<div class="placeholder">还没有捕捉宝可梦</div>'; E.reserveCount.textContent = `${me.reserved.length} / 3`; E.myReserved.innerHTML = me.reserved.map(c => cardHtml(c, "reserved")).join("") || '<div class="placeholder">没有保留卡</div>';
  const messages = { lobby: "等待房主开始挑战", action: myTurn ? "请选择一项主要操作" : `等待 ${turn?.name} 行动`, discard: myTurn ? "请归还超出上限的精灵球" : `${turn?.name} 正在归还精灵球`, evolve: myTurn ? "可以进化一只宝可梦，或跳过" : `${turn?.name} 正在选择进化` }; E.notice.textContent = v.phase === "ended" ? `${v.winners.map(id => v.players.find(p => p.id === id)?.name).join("、")} 获胜！` : messages[v.phase === "lobby" ? "lobby" : v.turnStage]; E.actionTitle.textContent = v.phase === "ended" ? "挑战结束" : messages[v.phase === "lobby" ? "lobby" : v.turnStage]; E.phaseBadge.textContent = v.endTriggered ? "最后一轮" : v.phase === "playing" ? `第 ${v.round} 轮` : "准备阶段"; renderActions(v, me, myTurn); bindCards(v, me, myTurn)
}
function renderActions(v, me, myTurn) { E.actionArea.innerHTML = ""; E.selectionSummary.textContent = ""; if (!myTurn) return; if (v.turnStage === "action") { const available = COLORS.filter(c => v.supply[c] > 0), need = Math.min(3, available.length); E.selectionSummary.textContent = selection.length ? `已选择：${selection.map(c => NAMES[c]).join("、")}` : `选择 ${need} 种不同颜色，或点击一种供应量至少为4的颜色`; button(`拿取 ${need} 种不同颜色`, () => submit({ type: "takeDifferent", colors: selection }), selection.length !== need); if (selection.length === 1) button(`拿取两个${NAMES[selection[0]]}`, () => submit({ type: "takeSame", color: selection[0] }), v.supply[selection[0]] < 4) } else if (v.turnStage === "discard") { button("选择要归还的精灵球", () => openDiscard(me)) } else if (v.turnStage === "evolve") { const opts = evolvableView(v, me); opts.forEach(x => button(`进化为 ${x.card.name}`, () => submit({ type: "evolve", cardId: x.card.id, source: x.source }))); button("跳过进化并结束回合", () => submit({ type: "skipEvolve" })) } }
function button(text, on, disabled = false) { const b = document.createElement("button"); b.textContent = text; b.disabled = disabled; b.onclick = on; E.actionArea.appendChild(b) }
function evolvableView(v, p) { const out = []; for (const [kind, list] of Object.entries(v.market || {})) for (const card of list) if (canEvolveView(p, card)) out.push({ card, source: "market", kind }); for (const card of p.reserved) if (canEvolveView(p, card)) out.push({ card, source: "reserved" }); return out }
function canEvolveView(p, c) { return c && !c.hidden && c.evolvesFrom && p.pokemon.some(x => x.name === c.evolvesFrom) && Object.entries(c.evolutionCost).every(([k, n]) => (p.bonuses[k] || 0) >= n) }
function bindCards(v, me, myTurn) { E.tokens.querySelectorAll("[data-token]").forEach(b => b.onclick = () => { const c = b.dataset.token; if (selection.includes(c)) selection = selection.filter(x => x !== c); else if (selection.length < 3) selection.push(c); render() }); if (!myTurn || v.turnStage !== "action") return; document.querySelectorAll(".poke-card[data-card]").forEach(el => el.onclick = () => { const id = el.dataset.card, marketEntry = Object.entries(v.market).flatMap(([kind, list]) => list.map(card => ({ card, kind }))).find(x => x.card.id === id), reserved = me.reserved.find(c => c.id === id); if (marketEntry) openCardActions(me, marketEntry.card, marketEntry.kind, "market"); else if (reserved) openCardActions(me, reserved, null, "reserved") }); document.querySelectorAll("[data-blind]").forEach(d => d.onclick = () => { const tier = d.dataset.blind; if (me.reserved.length >= 3) return alert("最多保留三张卡。"); if (!v.decks[tier]) return alert("该牌库已空。"); confirmAction(`暗中保留等级 ${tier} 牌库顶卡？`, () => submit({ type: "reserve", blind: true, kind: tier })) }) }
function openCardActions(me, card, kind, source) { E.modalTitle.textContent = card.name; E.modalBody.innerHTML = cardHtml(card); E.modalActions.innerHTML = ""; const cap = document.createElement("button"); cap.className = "primary"; cap.textContent = "捕捉"; cap.onclick = () => openPayment(me, card, kind, source); E.modalActions.appendChild(cap); if (source === "market" && ["1", "2", "3"].includes(String(kind))) { const reserve = document.createElement("button"); reserve.textContent = "保留"; reserve.disabled = me.reserved.length >= 3; reserve.onclick = () => { closeModal(); submit({ type: "reserve", cardId: card.id, kind: String(kind) }) }; E.modalActions.appendChild(reserve) } buttonModal("取消", closeModal) }
function openPayment(me, card, kind, source) { const need = {}; for (const [c, n] of Object.entries(card.cost)) need[c] = c === "master" ? n : Math.max(0, n - (me.bonuses[c] || 0)); const mandatory = need.master || 0, deficits = mandatory + COLORS.reduce((s, c) => s + Math.max(0, (need[c] || 0) - me.tokens[c]), 0); if (deficits > me.tokens.master) return alert("精灵球不足，无法捕捉。"); const pay = emptyTokens(); for (const c of COLORS) pay[c] = Math.min(need[c] || 0, me.tokens[c]); pay.master = mandatory + COLORS.reduce((s, c) => s + (need[c] || 0) - pay[c], 0); E.modalTitle.textContent = `支付方案 · ${card.name}`; E.modalBody.innerHTML = `<p>永久奖励已自动抵扣。点击普通球可以改用大师球替代。</p><div id="payChoices" class="resource-strip"></div>`; const draw = () => { $("payChoices").innerHTML = COLORS.filter(c => need[c]).map(c => `<button data-pay="${c}" ${pay[c] <= 0 ? "disabled" : ""}>${NAMES[c]} ${pay[c]} / ${need[c]}</button>`).join("") + orbHtml("master", pay.master); $("payChoices").querySelectorAll("[data-pay]").forEach(b => b.onclick = () => { const c = b.dataset.pay; if (pay[c] > 0 && pay.master < me.tokens.master) { pay[c]--; pay.master++; draw() } }) }; draw(); E.modalActions.innerHTML = ""; buttonModal("确认捕捉", () => { closeModal(); submit({ type: "capture", cardId: card.id, kind: String(kind), source, payment: pay }) }, "primary"); buttonModal("取消", closeModal) }
function openDiscard(me) { const excess = Object.values(me.tokens).reduce((a, b) => a + b, 0) - 10, give = emptyTokens(); E.modalTitle.textContent = `归还 ${excess} 个精灵球`; E.modalBody.innerHTML = '<div id="discardChoices" class="resource-strip"></div><p id="discardStatus"></p>'; const draw = () => { $("discardChoices").innerHTML = [...COLORS, "master"].map(c => `<button data-give="${c}" ${give[c] >= me.tokens[c] ? "disabled" : ""}>${NAMES[c]} ${give[c]} / ${me.tokens[c]}</button>`).join(""); $("discardStatus").textContent = `还需选择 ${excess - Object.values(give).reduce((a, b) => a + b, 0)} 个`; $("discardChoices").querySelectorAll("[data-give]").forEach(b => b.onclick = () => { const c = b.dataset.give, total = Object.values(give).reduce((a, b) => a + b, 0); if (total < excess) { give[c]++; draw() } }) }; draw(); E.modalActions.innerHTML = ""; buttonModal("确认归还", () => { if (Object.values(give).reduce((a, b) => a + b, 0) !== excess) return; closeModal(); submit({ type: "discard", tokens: give }) }, "primary"); buttonModal("重新选择", () => { Object.keys(give).forEach(c => give[c] = 0); draw() }) }
function confirmAction(text, fn) { if (confirm(text)) fn() } function buttonModal(text, on, klass = "") { const b = document.createElement("button"); b.textContent = text; b.className = klass; b.onclick = on; E.modalActions.appendChild(b) } function closeModal() { E.modal.classList.add("hidden") }
async function init() { try { if ((await fetch("/api/config", { cache: "no-store" })).ok) E.connectionStatus.textContent = "联机服务可用" } catch { E.connectionStatus.textContent = "请通过 signal-server.js 打开" } E.hostModeButton.onclick = () => setMode("host"); E.guestModeButton.onclick = () => setMode("guest"); E.createRoomButton.onclick = createRoom; E.joinRoomButton.onclick = joinRoom; E.roomCodeInput.oninput = () => E.roomCodeInput.value = E.roomCodeInput.value.toUpperCase().replace(/[^A-Z0-9]/g, ""); E.roomPlayerCountSelect.onchange = changeCapacity; E.startGameButton.onclick = startGame; E.endGameButton.onclick = endGame; E.toggleLogButton.onclick = () => E.logList.classList.toggle("collapsed"); E.modal.onclick = e => { if (e.target === E.modal) closeModal() }; setMode("host") } init();
