"use strict";
const PROTOCOL_VERSION=1,ACTION_SECONDS=60,MARKET=[0,5,10,20,30];
const GOODS={
 ginseng:{name:"人参",icon:"🌿",color:"#d0a33b",payout:18,seats:[1,2,3],die:[1,1,2,2,3,3]},
 nutmeg:{name:"肉豆蔻",icon:"🌰",color:"#a5653d",payout:24,seats:[2,3,4],die:[1,2,2,3,3,4]},
 silk:{name:"丝绸",icon:"🧵",color:"#527ed1",payout:30,seats:[3,4,5],die:[1,3,3,4,4,5]},
 jade:{name:"玉石",icon:"💎",color:"#2d9c72",payout:36,seats:[3,4,5,6],die:[3,3,4,4,5,5]}
};
const BETS=[{id:"A",cost:4,payout:6},{id:"B",cost:3,payout:8},{id:"C",cost:2,payout:15}],PLAYER_COLORS=["#e4564f","#356fc2","#e9a72d","#369b69","#8a59bd"];
let mode="host",selfId="",roomCode="",hostId="",resumeToken="",events=null,state=null,guestView=null,clock=null,hostTimer=null;
const $=id=>document.getElementById(id),E={connectionStatus:$("connectionStatus"),setupPanel:$("setupPanel"),roomPanel:$("roomPanel"),hostModeButton:$("hostModeButton"),guestModeButton:$("guestModeButton"),hostSetup:$("hostSetup"),guestSetup:$("guestSetup"),hostNameInput:$("hostNameInput"),guestNameInput:$("guestNameInput"),playerCountSelect:$("playerCountSelect"),createRoomButton:$("createRoomButton"),joinRoomButton:$("joinRoomButton"),roomCodeInput:$("roomCodeInput"),roomCodeDisplay:$("roomCodeDisplay"),hostTools:$("hostTools"),roomPlayerCountSelect:$("roomPlayerCountSelect"),startGameButton:$("startGameButton"),endGameButton:$("endGameButton"),phaseText:$("phaseText"),myCash:$("myCash"),myShares:$("myShares"),mortgageButton:$("mortgageButton"),redeemButton:$("redeemButton"),playerList:$("playerList"),playerCountBadge:$("playerCountBadge"),marketGrid:$("marketGrid"),portSlots:$("portSlots"),yardSlots:$("yardSlots"),routes:$("routes"),pirateSlots:$("pirateSlots"),pilotSlots:$("pilotSlots"),insuranceSlot:$("insuranceSlot"),actionTitle:$("actionTitle"),notice:$("notice"),actionArea:$("actionArea"),timerText:$("timerText"),timerBar:$("timerBar"),logList:$("logList"),toggleLogButton:$("toggleLogButton")};
const uid=p=>`${p}_${Math.random().toString(36).slice(2,10)}`,clean=(v,f)=>String(v||"").trim().slice(0,12)||f,esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const sessionKey=code=>`tablegame:manila:${code}`,loadSession=code=>{try{return JSON.parse(localStorage.getItem(sessionKey(code))||"null")}catch{return null}},saveSession=name=>localStorage.setItem(sessionKey(roomCode),JSON.stringify({playerId:selfId,resumeToken,name})),clearSession=()=>roomCode&&localStorage.removeItem(sessionKey(roomCode));
function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
async function post(path,data){const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)}),j=await r.json();if(!r.ok)throw Error(j.error||"request failed");return requireProtocol(j)}
function requireProtocol(r){if(r?.protocolVersion!==PROTOCOL_VERSION)throw Error(`联机协议不匹配，需要 v${PROTOCOL_VERSION}`);return r}
async function signal(to,payload){return post("/api/signal",{roomCode,from:selfId,resumeToken,to,payload})}
function openEvents(id){return new Promise((resolve,reject)=>{events?.close();events=new EventSource(`/api/events?clientId=${encodeURIComponent(id)}&roomCode=${encodeURIComponent(roomCode)}&resumeToken=${encodeURIComponent(resumeToken)}`);let ready=false;events.addEventListener("open",()=>{ready=true;E.connectionStatus.textContent=`已连接房间 ${roomCode}`;resolve()},{once:true});events.addEventListener("signal",e=>receive(JSON.parse(e.data)));events.addEventListener("error",()=>{E.connectionStatus.textContent="联机服务正在重连";if(!ready)reject(Error("SSE connection failed"))})})}
function receive(message){const p=message.payload||{};if(mode==="host"){if(p.kind==="join"||p.kind==="hello")admit(message.from,p.name);else if(p.kind==="presence")setPresence(p.playerId,p.connected);else if(p.kind==="action")apply(message.from,p.action)}else{if(p.kind==="view"){guestView=p.view;render()}else if(p.kind==="rejected"){alert(p.message);location.reload()}else if(p.kind==="kicked"){clearSession();events?.close();alert("你已被房主移出房间");location.reload()}}}
function setMode(next){mode=next;E.hostModeButton.classList.toggle("active",next==="host");E.guestModeButton.classList.toggle("active",next==="guest");E.hostSetup.classList.toggle("hidden",next!=="host");E.guestSetup.classList.toggle("hidden",next!=="guest")}
function player(id,name,isHost=false,index=0){return{id,name,isHost,color:PLAYER_COLORS[index],cash:30,shares:[],assistants:3,connected:true}}
function freshState(capacity){const goods=Object.keys(GOODS),deck=shuffle(goods.flatMap(g=>Array(3).fill(g))),p=player(selfId,clean(E.hostNameInput.value,"房主"),true,0);p.shares=deck.splice(0,2).map(g=>({good:g,initial:true,mortgaged:false}));const stock=Object.fromEntries(goods.map(g=>[g,5-p.shares.filter(s=>s.good===g).length]));return{phase:"lobby",capacity,players:[p],stock,market:Object.fromEntries(goods.map(g=>[g,0])),voyage:0,harborMasterId:null,previousMasterId:null,auctionStarter:0,auctionTurn:0,highBid:0,highBidder:null,passed:[],ships:[],placements:[],port:[],yard:[],logs:[],deadline:0,pending:null}}
async function createRoom(){selfId=uid("host");hostId=selfId;state=freshState(Number(E.playerCountSelect.value));try{const r=await post("/api/rooms",{hostId:selfId,name:state.players[0].name});roomCode=r.roomCode;resumeToken=r.resumeToken;await openEvents(selfId);enter();render()}catch(e){alert(`创建失败：${e.message}`)}}
async function joinRoom(){roomCode=E.roomCodeInput.value.trim().toUpperCase();const saved=loadSession(roomCode);selfId=saved?.playerId||uid("guest");try{const name=saved?.name||clean(E.guestNameInput.value,"玩家"),r=await post("/api/join",{roomCode,clientId:selfId,resumeToken:saved?.resumeToken,name:saved?"":name});selfId=r.clientId;resumeToken=r.resumeToken;hostId=r.hostId;await openEvents(selfId);await signal(hostId,{kind:"join",name,resumed:r.resumed});saveSession(name);enter()}catch(e){alert(`加入失败：${e.message}`)}}
function enter(){E.setupPanel.classList.add("hidden");E.roomPanel.classList.remove("hidden");E.hostTools.classList.toggle("hidden",mode!=="host")}
function admit(id,name){const old=state.players.find(p=>p.id===id);if(old){old.connected=true;return sync()}if(state.phase!=="lobby")return signal(id,{kind:"rejected",message:"游戏已经开始"});if(state.players.length>=state.capacity)return signal(id,{kind:"rejected",message:"房间已满"});state.players.push(player(id,clean(name,"玩家"),false,state.players.length));sync()}
function log(text){state.logs.unshift(text);state.logs=state.logs.slice(0,100)}
function current(){return mode==="host"?(state?buildView(selfId):null):guestView}
function broadcast(){if(mode!=="host")return;state.players.filter(p=>p.id!==selfId).forEach(p=>signal(p.id,{kind:"view",view:buildView(p.id)}).catch(()=>p.connected=false))}
function sync(){render();broadcast();scheduleTimeout()}
function scheduleTimeout(){clearTimeout(hostTimer);if(mode!=="host")return;const actor=activePlayer(state);if(actor&&!state.players.find(p=>p.id===actor)?.connected){hostTimer=setTimeout(()=>resolveOfflineActor(actor),0);return}if(!state.deadline)return;const ms=Math.max(0,state.deadline-Date.now()+100);hostTimer=setTimeout(handleTimeout,ms)}
function randomStarts(){let a,b,c;do{a=Math.floor(Math.random()*6);b=Math.floor(Math.random()*6);c=9-a-b}while(c<0||c>5);return[a,b,c]}
function resolveOfflineActor(id){if(mode!=="host"||state.players.find(p=>p.id===id)?.connected)return;if(state.phase==="auction"){if(!state.passed.includes(id))state.passed.push(id);return nextAuction()}if(state.phase==="configure")return configure({goods:shuffle(Object.keys(GOODS)).slice(0,3),starts:randomStarts(),buyGood:null});if(state.phase==="placing"){const p=state.players.find(x=>x.id===id),opts=placementOptions().filter(x=>x.type!=="insurance"||availableFunds(p)>0),opt=opts[Math.floor(Math.random()*opts.length)];return opt?place(p,{placeType:opt.type,index:opt.index}):advancePlacement()}if(state.phase==="arrivalOrder")return resolveArrivalOrder(shuffle(state.pending.arrivals));if(state.phase==="yardOrder")return finishDestinations(shuffle(state.pending.failures));if(state.phase==="pilot")return pilotMove({skip:true});if(state.phase==="pirateBoard")return pirateBoard({skip:true});if(state.phase==="plunder")return plunderChoice({destination:Math.random()<.5?"port":"yard"})}
function setPresence(id,connected){const p=state?.players.find(x=>x.id===id);if(!p||p.connected===connected)return;p.connected=connected;sync()}
async function kickPlayer(id){const p=state?.players.find(x=>x.id===id);if(!p||p.isHost||!confirm(`确定要移出 ${p.name} 吗？`))return;try{await post("/api/kick",{roomCode,hostId:selfId,resumeToken,playerId:id});state.players=state.players.filter(x=>x.id!==id);clearDeadline();Object.assign(state,{phase:"lobby",harborMasterId:null,previousMasterId:null,highBid:0,highBidder:null,passed:[],ships:[],placements:[],port:[],yard:[],deadline:0,pending:null});log(`${p.name} 被房主移出，当前航行已结束`);sync()}catch{alert("无法移出该玩家，请检查服务器连接")}}
function timed(seconds=ACTION_SECONDS){state.deadline=Date.now()+seconds*1000}
function clearDeadline(){state.deadline=0;clearTimeout(hostTimer)}
function buildView(viewer){const me=state.players.find(p=>p.id===viewer),reveal=state.phase==="ended";return{...state,selfId:viewer,players:state.players.map(p=>({...p,cash:p.id===viewer||reveal?p.cash:null,shares:p.shares.map(s=>p.id===viewer||reveal||!s.initial?{...s}:{hidden:true})})),privateCash:me?.cash||0}}
function startGame(){if(state.players.length!==state.capacity)return alert(`需要 ${state.capacity} 人到齐`);dealInitialShares();state.voyage=0;state.previousMasterId=null;startAuction()}
function dealInitialShares(){const goods=Object.keys(GOODS),deck=shuffle(goods.flatMap(g=>Array(3).fill(g)));state.players.forEach(p=>{p.cash=30;p.shares=deck.splice(0,2).map(g=>({good:g,initial:true,mortgaged:false}));p.assistants=3});state.stock=Object.fromEntries(goods.map(g=>[g,5-state.players.flatMap(p=>p.shares).filter(s=>s.good===g).length]));state.market=Object.fromEntries(goods.map(g=>[g,0]))}
function startAuction(){state.voyage++;state.phase="auction";state.ships=[];state.placements=[];state.port=[];state.yard=[];state.highBid=0;state.highBidder=null;state.passed=[];state.auctionStarter=state.previousMasterId?state.players.findIndex(p=>p.id===state.previousMasterId):Math.floor(Math.random()*state.players.length);state.auctionTurn=state.auctionStarter;state.deadline=0;log(`第 ${state.voyage} 次航行：开始竞拍港务长`);sync()}
function availableFunds(p){return p.cash+p.shares.filter(s=>!s.mortgaged).length*12}
function nextAuction(){const alive=state.players.filter(p=>p.connected&&!state.passed.includes(p.id));if(alive.length<=1){const winner=state.highBidder||alive[0]?.id||state.previousMasterId||state.players.find(p=>p.connected)?.id;const p=state.players.find(x=>x.id===winner);if(!p)return;if(state.highBid){ensureCash(p,state.highBid);p.cash-=state.highBid}state.harborMasterId=winner;state.previousMasterId=winner;state.phase="configure";log(`${p.name} 以 ${state.highBid} 比索成为港务长`);return sync()}for(let n=1;n<=state.players.length;n++){const i=(state.auctionTurn+n)%state.players.length,p=state.players[i];if(p.connected&&!state.passed.includes(p.id)){state.auctionTurn=i;break}}sync()}
function configure(a){const master=state.players.find(p=>p.id===state.harborMasterId),selected=a.goods||[],starts=(a.starts||[]).map(Number);if(selected.length!==3||new Set(selected).size!==3||starts.length!==3||starts.some(n=>n<0||n>5)||starts.reduce((x,y)=>x+y,0)!==9)return;if(a.buyGood){const price=Math.max(5,MARKET[state.market[a.buyGood]]);if(!state.stock[a.buyGood]||availableFunds(master)<price)return;ensureCash(master,price);master.cash-=price;master.shares.push({good:a.buyGood,initial:false,mortgaged:false});state.stock[a.buyGood]--}state.ships=selected.map((g,i)=>({good:g,position:starts[i],arrived:false,destination:null,workers:[],die:null}));state.phase="placing";state.placementRound=1;state.placeTurn=state.players.findIndex(p=>p.id===state.harborMasterId);log(`港务长装载了${selected.map(g=>GOODS[g].name).join("、")}`);sync()}
function placementOptions(){const out=[];state.ships.forEach((s,si)=>{if(s.workers.length<GOODS[s.good].seats.length)out.push({type:"ship",index:si,cost:GOODS[s.good].seats[s.workers.length]})});BETS.forEach((b,i)=>{if(!state.placements.some(x=>x.type==="port"&&x.index===i))out.push({type:"port",index:i,cost:b.cost});if(!state.placements.some(x=>x.type==="yard"&&x.index===i))out.push({type:"yard",index:i,cost:b.cost})});[0,1].forEach(i=>{if(!state.placements.some(x=>x.type==="pirate"&&x.index===i))out.push({type:"pirate",index:i,cost:5})});[{index:0,cost:2},{index:1,cost:5}].forEach(x=>{if(!state.placements.some(p=>p.type==="pilot"&&p.index===x.index))out.push({type:"pilot",...x})});if(!state.placements.some(x=>x.type==="insurance"))out.push({type:"insurance",index:0,cost:-10});return out}
function place(p,a){if(p.assistants<=0)return;const opt=placementOptions().find(x=>x.type===a.placeType&&x.index===Number(a.index));if(!opt||opt.type==="insurance"&&availableFunds(p)===0)return;let cost=opt.cost;if(cost>availableFunds(p)){const cheapest=Math.min(...placementOptions().filter(x=>x.type!=="insurance").map(x=>Math.max(0,x.cost)));if(availableFunds(p)>=cheapest)return;cost=Math.max(0,p.cash);while(p.cash<cost&&p.shares.some(s=>!s.mortgaged))mortgage(p,p.shares.findIndex(s=>!s.mortgaged))}else if(cost>0)ensureCash(p,cost);p.cash-=Math.max(0,cost);if(cost<0)p.cash-=cost;p.assistants--;const item={type:opt.type,index:opt.index,playerId:p.id,order:state.placements.length};state.placements.push(item);if(opt.type==="ship")state.ships[opt.index].workers.push(item);log(`${p.name} 派助手前往${placeName(item)}`);advancePlacement()}
function advancePlacement(){state.placeTurn=(state.placeTurn+1)%state.players.length;if(state.placeTurn===state.players.findIndex(p=>p.id===state.harborMasterId)){if(state.placementRound>=3)return beforeRoll(3);const round=state.placementRound;rollShips(round);state.placementRound++;state.placeTurn=state.players.findIndex(p=>p.id===state.harborMasterId)}sync()}
function beforeRoll(round){if(round===3&&state.placements.some(x=>x.type==="pilot")){state.phase="pilot";state.pending={pilotIndex:0};return startNextPilot()}rollShips(round)}
function startNextPilot(){const pilots=state.placements.filter(x=>x.type==="pilot").sort((a,b)=>a.index-b.index),p=pilots[state.pending.pilotIndex];if(!p)return rollShips(3);state.pending.playerId=p.playerId;timed();sync()}
function pilotMove(a){const p=state.placements.filter(x=>x.type==="pilot").sort((x,y)=>x.index-y.index)[state.pending.pilotIndex],moves=a.skip?[]:(a.moves||[]);const allowance=p.index===0?1:2;if(moves.length>allowance)return;for(const m of moves){const ship=state.ships[Number(m.ship)];if(!ship||ship.arrived||Math.abs(Number(m.delta))!==1)return}moves.forEach(m=>moveShip(state.ships[Number(m.ship)],Number(m.delta),true));state.pending.pilotIndex++;startNextPilot()}
function rollShips(round){state.phase="rolling";state.rollRound=round;state.ships.filter(s=>!s.arrived).forEach(s=>{const faces=GOODS[s.good].die;s.die=faces[Math.floor(Math.random()*faces.length)]});log(`第 ${round} 轮骰点：${state.ships.filter(s=>!s.arrived).map(s=>`${GOODS[s.good].name}${s.die}`).join("、")}`);const arrivals=state.ships.map((s,i)=>({s,i})).filter(x=>!x.s.arrived&&x.s.position+x.s.die>13).map(x=>x.i);state.pending={arrivals,round};if(arrivals.length>1){state.phase="arrivalOrder";timed();sync()}else{arrivals.forEach(i=>moveShip(state.ships[i],state.ships[i].die));finishRoll()}}
function resolveArrivalOrder(order){const valid=(order||[]).map(Number);if(valid.length!==state.pending.arrivals.length||new Set(valid).size!==valid.length||valid.some(i=>!state.pending.arrivals.includes(i)))return;valid.forEach(i=>moveShip(state.ships[i],state.ships[i].die));finishRoll()}
function moveShip(ship,delta,pilot=false){if(ship.arrived)return;ship.position+=delta;if(ship.position>13){ship.arrived=true;ship.destination="port";state.port.push(ship.good);log(`${GOODS[ship.good].name}船${pilot?"由领航员送入":"驶入"}港口 ${String.fromCharCode(64+state.port.length)}`)}}
function finishRoll(){clearDeadline();state.ships.filter(s=>!s.arrived&&!state.pending.arrivals.includes(state.ships.indexOf(s))).forEach(s=>moveShip(s,s.die));const round=state.pending.round;if(round===2){const targets=state.ships.map((s,i)=>({s,i})).filter(x=>!x.s.arrived&&x.s.position===13).map(x=>x.i),pirates=state.placements.filter(x=>x.type==="pirate");if(targets.length&&pirates.length){state.phase="pirateBoard";state.pending={targets,pirates,pirateIndex:0,round};timed();return sync()}}if(round<3){state.phase="placing";return sync()}resolveFinal()}
function pirateBoard(a){const pirate=state.pending.pirates[state.pending.pirateIndex];if(!a.skip){const si=Number(a.ship),ship=state.ships[si];if(!state.pending.targets.includes(si)||!ship)return;let removed=null;if(ship.workers.length>=GOODS[ship.good].seats.length){const ri=ship.workers.findLastIndex(w=>!w.boardedPirate);if(ri<0)return;removed=ship.workers.splice(ri,1)[0]}if(removed){const rp=state.players.find(p=>p.id===removed.playerId);rp.assistants++;state.placements=state.placements.filter(x=>x!==removed);log(`${rp.name} 最后一名普通助手被海盗踢下船`)}state.placements=state.placements.filter(x=>x!==pirate);pirate.type="ship";pirate.index=si;pirate.boardedPirate=true;ship.workers.push(pirate);log(`${nameOf(pirate.playerId)} 的海盗登上${GOODS[ship.good].name}船`)}state.pending.pirateIndex++;if(state.pending.pirateIndex>=state.pending.pirates.length){state.phase="placing";clearDeadline();return sync()}timed();sync()}
function resolveFinal(){const plunder=state.ships.map((s,i)=>({s,i})).filter(x=>!x.s.arrived&&x.s.position===13).map(x=>x.i),pirates=state.placements.filter(x=>x.type==="pirate").sort((a,b)=>a.index-b.index);if(plunder.length&&pirates.length){state.phase="plunder";state.pending={ships:plunder,pirates,choiceIndex:0};timed();return sync()}plunder.forEach(i=>{const s=state.ships[i];s.arrived=true;s.destination="port";state.port.push(s.good);log(`${GOODS[s.good].name}船停在13格且没有海盗，视为成功进港`)});prepareYard()}
function plunderChoice(a){const si=state.pending.ships[state.pending.choiceIndex],ship=state.ships[si],dest=a.destination==="yard"?"yard":"port";ship.workers.forEach(w=>{state.players.find(p=>p.id===w.playerId).assistants++;state.placements=state.placements.filter(x=>x!==w)});ship.workers=[];ship.plunderedBy=state.pending.pirates.map(p=>p.playerId);ship.arrived=true;ship.destination=dest;if(dest==="port")state.port.push(ship.good);log(`${GOODS[ship.good].name}船被劫掠并送往${dest==="port"?"港口":"修船厂"}`);state.pending.choiceIndex++;if(state.pending.choiceIndex<state.pending.ships.length){timed();return sync()}prepareYard()}
function prepareYard(){const failures=state.ships.map((s,i)=>({s,i})).filter(x=>!x.s.arrived).map(x=>x.i);if(failures.length>1){state.phase="yardOrder";state.pending={failures};timed();return sync()}finishDestinations(failures)}
function finishDestinations(order){for(const i of order){const s=state.ships[i];s.arrived=true;s.destination="yard";state.yard.push(s.good)}state.ships.filter(s=>s.destination==="yard"&&!state.yard.includes(s.good)).forEach(s=>state.yard.push(s.good));settle()}
function settle(){clearDeadline();state.phase="settling";for(const s of state.ships){if(s.plunderedBy){const each=Math.floor(GOODS[s.good].payout/s.plunderedBy.length);s.plunderedBy.forEach(id=>state.players.find(p=>p.id===id).cash+=each)}else if(s.destination==="port"&&s.workers.length){const each=GOODS[s.good].payout/s.workers.length;s.workers.forEach(w=>state.players.find(p=>p.id===w.playerId).cash+=each)}}for(const type of ["port","yard"]){const list=type==="port"?state.port:state.yard;BETS.forEach((b,i)=>{if(!list[i])return;const bet=state.placements.find(x=>x.type===type&&x.index===i);if(type==="port"){if(bet)state.players.find(p=>p.id===bet.playerId).cash+=b.payout}else payInsurance(b.payout,bet?.playerId)})}state.port.forEach(g=>state.market[g]=Math.min(4,state.market[g]+1));state.players.forEach(p=>p.assistants=3);log(`第 ${state.voyage} 次航行结算完成`);if(Object.values(state.market).some(i=>i===4)){state.phase="ended";return sync()}startAuction()}
function payInsurance(amount,toId){const agent=state.placements.find(x=>x.type==="insurance"),payer=agent&&state.players.find(p=>p.id===agent.playerId);if(!payer){if(toId)state.players.find(p=>p.id===toId).cash+=amount;return}let paid=Math.min(amount,availableFunds(payer));ensureCash(payer,paid);payer.cash-=paid;if(toId)state.players.find(p=>p.id===toId).cash+=amount}
function mortgage(p,index){const s=p.shares[index];if(!s||s.mortgaged)return;s.mortgaged=true;p.cash+=12}
function redeem(p,index){const s=p.shares[index];if(!s||!s.mortgaged||p.cash<15)return;s.mortgaged=false;p.cash-=15}
function ensureCash(p,amount){while(p.cash<amount&&p.shares.some(s=>!s.mortgaged))mortgage(p,p.shares.findIndex(s=>!s.mortgaged))}
function apply(id,a={}){const p=state.players.find(x=>x.id===id);if(!p)return;if(a.type==="mortgage"){mortgage(p,Number(a.index));return sync()}if(a.type==="redeem"){redeem(p,Number(a.index));return sync()}if(state.phase==="auction"&&state.players[state.auctionTurn].id===id){if(a.action==="pass")state.passed.push(id);else{const bid=Number(a.bid);if(!Number.isInteger(bid)||bid<=state.highBid||bid>availableFunds(p))return;state.highBid=bid;state.highBidder=id}return nextAuction()}if(state.phase==="configure"&&id===state.harborMasterId)return configure(a);if(state.phase==="placing"&&state.players[state.placeTurn].id===id)return place(p,a);if(state.phase==="arrivalOrder"&&id===state.harborMasterId)return resolveArrivalOrder(a.order);if(state.phase==="pilot"&&id===state.pending.playerId)return pilotMove(a);if(state.phase==="pirateBoard"&&id===state.pending.pirates[state.pending.pirateIndex].playerId)return pirateBoard(a);if(state.phase==="plunder"&&id===state.pending.pirates[0].playerId)return plunderChoice(a);if(state.phase==="yardOrder"&&id===state.harborMasterId)return finishDestinations(a.order||[])}
function submit(action){if(mode==="host")apply(selfId,action);else signal(hostId,{kind:"action",action}).catch(()=>E.connectionStatus.textContent="操作发送失败")}
function handleTimeout(){if(state.phase==="pilot")pilotMove({skip:true});else if(state.phase==="pirateBoard")pirateBoard({skip:true});else if(state.phase==="plunder")plunderChoice({destination:Math.random()<.5?"port":"yard"});else if(state.phase==="arrivalOrder")resolveArrivalOrder(shuffle(state.pending.arrivals));else if(state.phase==="yardOrder")finishDestinations(shuffle(state.pending.failures))}
function nameOf(id){return state.players.find(p=>p.id===id)?.name||"玩家"}
function placeName(x){if(x.type==="ship")return `${GOODS[state.ships[x.index].good].name}船`;if(x.type==="port")return `港口 ${BETS[x.index].id}`;if(x.type==="yard")return `修船厂 ${BETS[x.index].id}`;return{pirate:"海盗船",pilot:x.index?"大领航员":"小领航员",insurance:"保险公司"}[x.type]}
function endGame(){if(!confirm("确定结束当前游戏并返回大厅吗？"))return;clearDeadline();state=freshState(state.capacity);sync()}

function meeple(id,v){const p=v.players.find(x=>x.id===id);return `<span class="meeple" style="--pc:${p?.color||"#777"}">${esc((p?.name||"?")[0])}</span>`}
function render(){
 const v=current();if(!v)return;const me=v.players.find(p=>p.id===v.selfId),activeId=activePlayer(v);
 E.roomCodeDisplay.textContent=roomCode;E.roomPlayerCountSelect.value=String(v.capacity);E.roomPlayerCountSelect.disabled=v.phase!=="lobby";E.startGameButton.classList.toggle("hidden",v.phase!=="lobby");E.startGameButton.disabled=v.players.length!==v.capacity;E.endGameButton.classList.toggle("hidden",mode!=="host"||v.phase==="lobby");
 E.playerCountBadge.textContent=`${v.players.length} / ${v.capacity}`;E.myCash.textContent=me?.cash??v.privateCash;E.phaseText.textContent=`第 ${v.voyage||0} 航次 · ${phaseName(v.phase)}`;
 E.myShares.innerHTML=(me?.shares||[]).map((s,i)=>s.hidden?"":`<span class="share ${s.mortgaged?"mortgaged":""}" style="background:${GOODS[s.good].color}" title="${s.initial?"初始秘密股票":"公开购入股票"}">${GOODS[s.good].icon}${GOODS[s.good].name}${s.mortgaged?"·抵押":""}</span>`).join("");
 E.playerList.innerHTML=v.players.map(p=>{const publicShares=p.shares.filter(s=>!s.hidden&&!s.initial);return `<div class="player ${p.id===activeId?"turn":""}" style="--pc:${p.color}"><b>${esc(p.name)}${p.isHost?" · 房主":""}</b><span>${p.cash==null?"现金保密":`₱ ${p.cash}`} · 助手 ${p.assistants}</span><small>公开购入：${publicShares.map(s=>GOODS[s.good].name+(s.mortgaged?"(抵押)":"")).join("、")||"无"} · 初始股票保密</small></div>`}).join("");
 if(mode==="host")v.players.forEach((p,i)=>{if(!p.isHost){const b=document.createElement("button");b.type="button";b.textContent="移出";b.onclick=()=>kickPlayer(p.id);E.playerList.children[i]?.appendChild(b)}});renderMarket(v);renderBoard(v);renderAction(v,me);E.logList.innerHTML=v.logs.map(x=>`<p>${esc(x)}</p>`).join("");startClock(v.deadline);
}
function renderMarket(v){E.marketGrid.innerHTML=Object.entries(GOODS).map(([id,g])=>`<div class="commodity" style="--gc:${g.color}"><h3><span>${g.icon}${g.name}</span><b>₱${MARKET[v.market[id]]}</b></h3><div class="track">${MARKET.map((n,i)=>`<i class="${i===v.market[id]?"active":""}">${n}</i>`).join("")}</div><small>库存 ${v.stock[id]} · 船收益 ${g.payout}</small></div>`).join("")}
function renderBoard(v){
 E.portSlots.innerHTML=BETS.map((b,i)=>slotHtml(v,"port",i,`${b.id} · ₱${b.cost}→${b.payout}`,v.port[i])).join("");
 E.yardSlots.innerHTML=BETS.map((b,i)=>slotHtml(v,"yard",i,`${b.id} · ₱${b.cost}→${b.payout}`,v.yard[i])).join("");
 E.routes.innerHTML=v.ships.length?v.ships.map((s,i)=>{const canBoard=v.phase==="placing"&&v.players[v.placeTurn]?.id===v.selfId&&!s.arrived&&s.workers.length<GOODS[s.good].seats.length;return `<div class="route"><div class="boat" style="--gc:${GOODS[s.good].color}"><div class="boat-head"><span>${GOODS[s.good].icon}${GOODS[s.good].name}</span><span>${s.die?"🎲"+s.die:""} · ₱${GOODS[s.good].payout}</span></div><div class="boat-seats">${GOODS[s.good].seats.map((cost,j)=>{const worker=s.workers[j],available=canBoard&&j===s.workers.length;return `<button type="button" class="seat ${available?"available":""}" ${available?`data-place="ship" data-index="${i}" title="支付 ${cost} 比索上船"`:"disabled"}>${worker?meeple(worker.playerId,v):"₱"+cost}</button>`}).join("")}</div></div><div class="waves">${Array.from({length:14},(_,n)=>`<span class="wave ${!s.arrived&&s.position===n?"at":""}">${n}${!s.arrived&&s.position===n?"⛵":""}</span>`).join("")}${s.arrived?`<b>${s.destination==="port"?"⚓进港":"🔧进厂"}</b>`:""}</div></div>`}).join(""):'<p>港务长尚未装载货船。</p>';
 E.pirateSlots.innerHTML=[0,1].map(i=>slotHtml(v,"pirate",i,i?"海盗 ₱5":"船长 ₱5")).join("");
 E.pilotSlots.innerHTML=[slotHtml(v,"pilot",0,"小领航员 ₱2"),slotHtml(v,"pilot",1,"大领航员 ₱5")].join("");
 E.insuranceSlot.innerHTML=slotHtml(v,"insurance",0,"立即 +₱10");
}
function slotHtml(v,type,index,label,destination){const x=v.placements.find(p=>p.type===type&&p.index===index),can=v.phase==="placing"&&v.players[v.placeTurn]?.id===v.selfId&&!x;return `<button class="slot ${can?"available":""}" ${can?`data-place="${type}" data-index="${index}"`:"disabled"}><b>${label}</b><br>${x?meeple(x.playerId,v):destination?GOODS[destination]?.icon||"":""}</button>`}
function activePlayer(v){if(v.phase==="auction")return v.players[v.auctionTurn]?.id;if(v.phase==="configure"||v.phase==="arrivalOrder"||v.phase==="yardOrder")return v.harborMasterId;if(v.phase==="placing")return v.players[v.placeTurn]?.id;if(v.phase==="pilot")return v.pending?.playerId;if(v.phase==="pirateBoard")return v.pending?.pirates[v.pending.pirateIndex]?.playerId;if(v.phase==="plunder")return v.pending?.pirates[0]?.playerId;return null}
function phaseName(p){return{lobby:"等待开局",auction:"竞拍港务长",configure:"港务长规划",placing:"派遣助手",rolling:"货船航行",arrivalOrder:"决定进港顺序",pilot:"领航员行动",pirateBoard:"海盗登船",plunder:"海盗劫掠",yardOrder:"安排修船",settling:"收益结算",ended:"游戏结束"}[p]||p}
function renderAction(v,me){
 const active=activePlayer(v),mine=active===v.selfId;E.actionTitle.textContent=mine?"轮到你了":active?`等待 ${v.players.find(p=>p.id===active)?.name}`:phaseName(v.phase);E.actionArea.innerHTML="";
 if(v.phase==="lobby"){E.notice.textContent=v.players.length===v.capacity?"玩家到齐，房主可以开始。":`等待玩家加入：${v.players.length}/${v.capacity}`;return}
 if(v.phase==="ended"){const totals=v.players.map(p=>({name:p.name,total:(p.cash||0)+p.shares.reduce((sum,s)=>sum+(s.hidden?0:MARKET[v.market[s.good]])-(s.mortgaged?15:0),0)})),max=Math.max(...totals.map(x=>x.total));E.notice.textContent=`游戏结束：${totals.filter(x=>x.total===max).map(x=>x.name).join("、")} 并列获胜！`;return}
 E.notice.textContent=notice(v);if(!mine)return;
 if(v.phase==="auction"){E.actionArea.innerHTML=`<label>当前最高 ₱${v.highBid}<input id="bidInput" type="number" min="${v.highBid+1}" max="${availableViewFunds(me)}" value="${v.highBid+1}"></label><button id="bidButton" class="primary">出价</button><button id="passButton" class="small">退出竞拍</button>`;$("bidButton").onclick=()=>submit({type:"auction",action:"bid",bid:Number($("bidInput").value)});$("passButton").onclick=()=>submit({type:"auction",action:"pass"});return}
 if(v.phase==="configure"){renderConfigure(v);return}
 if(v.phase==="placing"){E.actionArea.innerHTML='<b>请在版图上点击一个空位放置助手。</b>';E.roomPanel.querySelectorAll("[data-place]").forEach(b=>b.onclick=()=>submit({type:"place",placeType:b.dataset.place,index:Number(b.dataset.index)}));return}
 if(v.phase==="arrivalOrder"||v.phase==="yardOrder"){const ids=v.phase==="arrivalOrder"?v.pending.arrivals:v.pending.failures;renderOrder(ids,v);return}
 if(v.phase==="pilot"){renderPilot(v);return}
 if(v.phase==="pirateBoard"){E.actionArea.innerHTML=v.pending.targets.map(i=>`<button class="choice-card" data-board="${i}">登上${GOODS[v.ships[i].good].name}船</button>`).join("")+'<button id="skipButton" class="small">留在海盗船</button>';E.actionArea.querySelectorAll("[data-board]").forEach(b=>b.onclick=()=>submit({type:"pirate",ship:Number(b.dataset.board)}));$("skipButton").onclick=()=>submit({type:"pirate",skip:true});return}
 if(v.phase==="plunder"){E.actionArea.innerHTML='<button id="toPort" class="primary">送进港口</button><button id="toYard" class="danger">送进修船厂</button>';$("toPort").onclick=()=>submit({type:"plunder",destination:"port"});$("toYard").onclick=()=>submit({type:"plunder",destination:"yard"});return}
}
function notice(v){if(v.phase==="auction")return `当前最高出价 ₱${v.highBid}。竞拍资金可由现金和抵押股票构成。`;if(v.phase==="configure")return "港务长可公开购买一张股票，然后选择三种货物与起点（总和必须为9）。";if(v.phase==="placing")return `第 ${v.placementRound}/3 次派遣，之后自动掷对应货物骰。`;if(v.phase==="pilot")return "领航员可影响尚未进港的船；一分钟后自动放弃。";if(v.phase==="pirateBoard")return "海盗可登上停在13格的船；满员时踢掉最后上船的助手。";if(v.phase==="plunder")return "海盗船长决定被劫船进入港口还是修船厂。";if(v.phase==="arrivalOrder")return "多艘船同轮抵港，由港务长决定进港顺序。";if(v.phase==="yardOrder")return "多艘船航行失败，由港务长决定修船厂 A/B/C 顺序。";return phaseName(v.phase)}
function availableViewFunds(p){return (p.cash||0)+p.shares.filter(s=>!s.hidden&&!s.mortgaged).length*12}
function renderConfigure(v){const goods=Object.entries(GOODS);E.actionArea.innerHTML=`<label>购买股票（可选）<select id="buyGood"><option value="">不购买</option>${goods.filter(([id])=>v.stock[id]).map(([id,g])=>`<option value="${id}">${g.name} ₱${Math.max(5,MARKET[v.market[id]])}</option>`).join("")}</select></label>${goods.map(([id,g])=>`<label class="choice-card"><input type="checkbox" name="cargo" value="${id}">${g.icon}${g.name}</label>`).join("")}${[0,1,2].map(i=>`<label>船${i+1}起点<input class="start-pos" type="number" min="0" max="5" value="3"></label>`).join("")}<button id="confirmConfig" class="primary">确认装船</button>`;$("confirmConfig").onclick=()=>submit({type:"configure",buyGood:$("buyGood").value||null,goods:[...document.querySelectorAll('[name="cargo"]:checked')].map(x=>x.value),starts:[...document.querySelectorAll(".start-pos")].map(x=>Number(x.value))})}
function renderOrder(ids,v){let order=[];E.actionArea.innerHTML=ids.map(i=>`<button class="choice-card" data-order="${i}">${GOODS[v.ships[i].good].icon}${GOODS[v.ships[i].good].name}</button>`).join("")+'<button id="confirmOrder" class="primary">确认顺序</button>';E.actionArea.querySelectorAll("[data-order]").forEach(b=>b.onclick=()=>{const i=Number(b.dataset.order);if(order.includes(i))return;order.push(i);b.classList.add("selected");b.textContent=`${order.length}. ${b.textContent}`});$("confirmOrder").onclick=()=>submit({type:"order",order})}
function renderPilot(v){const pilot=v.placements.filter(x=>x.type==="pilot").sort((a,b)=>a.index-b.index)[v.pending.pilotIndex],count=pilot?.index===1?2:1;E.actionArea.innerHTML=Array.from({length:count},(_,n)=>`<label>移动 ${n+1}<select class="pilot-ship">${v.ships.map((s,i)=>!s.arrived?`<option value="${i}">${GOODS[s.good].name}</option>`:"").join("")}</select><select class="pilot-delta"><option value="1">前进1格</option><option value="-1">后退1格</option></select></label>`).join("")+'<button id="pilotGo" class="primary">执行</button><button id="skipButton" class="small">放弃</button>';$("pilotGo").onclick=()=>submit({type:"pilot",moves:[...document.querySelectorAll(".pilot-ship")].map((x,i)=>({ship:Number(x.value),delta:Number(document.querySelectorAll(".pilot-delta")[i].value)}))});$("skipButton").onclick=()=>submit({type:"pilot",skip:true})}
function startClock(deadline){clearInterval(clock);const tick=()=>{if(!deadline){E.timerText.textContent="--";E.timerBar.style.width="0";return}const left=Math.max(0,deadline-Date.now());E.timerText.textContent=`${Math.ceil(left/1000)}s`;E.timerBar.style.width=`${left/(ACTION_SECONDS*10)}%`};tick();clock=setInterval(tick,200)}
async function init(){try{requireProtocol(await (await fetch("/api/config",{cache:"no-store"})).json());E.connectionStatus.textContent="联机服务可用"}catch{E.connectionStatus.textContent="请通过 signal-server.js 打开"}E.hostModeButton.onclick=()=>setMode("host");E.guestModeButton.onclick=()=>setMode("guest");E.createRoomButton.onclick=createRoom;E.joinRoomButton.onclick=joinRoom;E.roomCodeInput.oninput=()=>E.roomCodeInput.value=E.roomCodeInput.value.toUpperCase().replace(/[^A-Z0-9]/g,"");E.roomPlayerCountSelect.onchange=()=>{const n=Number(E.roomPlayerCountSelect.value);if(state&&state.phase==="lobby"&&n>=state.players.length){state.capacity=n;sync()}else E.roomPlayerCountSelect.value=state?.capacity||4};E.startGameButton.onclick=startGame;E.endGameButton.onclick=endGame;E.mortgageButton.onclick=()=>{const v=current(),me=v?.players.find(p=>p.id===v.selfId),i=me?.shares.findIndex(s=>!s.hidden&&!s.mortgaged);if(i>=0)submit({type:"mortgage",index:i})};E.redeemButton.onclick=()=>{const v=current(),me=v?.players.find(p=>p.id===v.selfId),i=me?.shares.findIndex(s=>!s.hidden&&s.mortgaged);if(i>=0)submit({type:"redeem",index:i})};E.toggleLogButton.onclick=()=>E.logList.classList.toggle("collapsed");setMode("host")}
init();
