"use strict";
const http=require("http"),fs=require("fs"),path=require("path"),{URL}=require("url");
const PROTOCOL_VERSION=1,port=Number(process.env.PORT||8793),root=__dirname;
const rooms=new Map(),clients=new Map(),pending=new Map(),alphabet="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
function json(res,status,data){res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"});res.end(JSON.stringify(data))}
function body(req){return new Promise((resolve,reject)=>{let value="";req.on("data",c=>{value+=c;if(value.length>1048576){req.destroy();reject(new Error("body too large"))}});req.on("end",()=>{try{resolve(value?JSON.parse(value):{})}catch(e){reject(e)}});req.on("error",reject)})}
function code(){for(let n=0;n<100;n++){let c="";for(let i=0;i<4;i++)c+=alphabet[Math.floor(Math.random()*alphabet.length)];if(!rooms.has(c))return c}throw Error("cannot allocate room")}
function push(id,event,data){const client=clients.get(id);if(!client){const q=pending.get(id)||[];q.push({event,data});pending.set(id,q.slice(-80));return false}client.res.write(`event: ${event}\n`);client.res.write(`data: ${JSON.stringify(data)}\n\n`);return true}
function file(res,pathname){const target=pathname==="/"?path.join(root,"index.html"):path.join(root,pathname),resolved=path.resolve(target);if(resolved!==root&&!resolved.startsWith(root+path.sep)){res.writeHead(403);return res.end("Forbidden")}fs.readFile(resolved,(e,data)=>{if(e){res.writeHead(404);return res.end("Not found")}const type={".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"text/javascript; charset=utf-8"}[path.extname(resolved)]||"application/octet-stream";res.writeHead(200,{"Content-Type":type,"Cache-Control":"no-store"});res.end(data)})}
async function api(req,res,url){
 if(req.method==="GET"&&url.pathname==="/api/config")return json(res,200,{relayMode:true,protocolVersion:PROTOCOL_VERSION});
 if(req.method==="GET"&&url.pathname==="/api/events"){const id=url.searchParams.get("clientId");if(!id)return json(res,400,{error:"clientId required"});res.writeHead(200,{"Content-Type":"text/event-stream; charset=utf-8","Cache-Control":"no-store",Connection:"keep-alive"});res.write(": connected\n\n");const heartbeat=setInterval(()=>res.write(": heartbeat\n\n"),15000);clients.set(id,{res,heartbeat});(pending.get(id)||[]).forEach(x=>push(id,x.event,x.data));pending.delete(id);req.on("close",()=>{const c=clients.get(id);if(c?.res===res){clearInterval(c.heartbeat);clients.delete(id)}});return}
 if(req.method==="POST"&&url.pathname==="/api/rooms"){const d=await body(req);if(!d.hostId)return json(res,400,{error:"hostId required"});const roomCode=code();rooms.set(roomCode,{hostId:d.hostId,createdAt:Date.now()});return json(res,200,{roomCode,protocolVersion:PROTOCOL_VERSION})}
 if(req.method==="POST"&&url.pathname==="/api/join"){const d=await body(req),roomCode=String(d.roomCode||"").toUpperCase(),room=rooms.get(roomCode);if(!room)return json(res,404,{error:"room not found"});return json(res,200,{roomCode,hostId:room.hostId,protocolVersion:PROTOCOL_VERSION})}
 if(req.method==="POST"&&url.pathname==="/api/signal"){const d=await body(req),roomCode=String(d.roomCode||"").toUpperCase();if(!rooms.has(roomCode))return json(res,404,{error:"room not found"});return json(res,200,{delivered:push(d.to,"signal",{roomCode,from:d.from,payload:d.payload}),protocolVersion:PROTOCOL_VERSION})}
 json(res,404,{error:"not found"})
}
http.createServer((req,res)=>{const url=new URL(req.url,`http://${req.headers.host}`);if(url.pathname.startsWith("/api/"))return api(req,res,url).catch(e=>json(res,500,{error:e.message}));file(res,decodeURIComponent(url.pathname))}).listen(port,()=>{console.log(`Manila: http://localhost:${port}`);console.log("Host-authoritative HTTP + SSE relay")});
