"use strict";
const SUITS=["♠","♥","♦","♣"],RANKS=[2,3,4,5,6,7,8,9,10,11,12,13,14];
const BLINDS=[[10,20],[15,30],[25,50],[40,80],[60,120],[100,200],[150,300],[250,500]];
let mode="host",selfId="",roomCode="",hostId="",events=null,state=null,guestView=null,actionTimer=null,countdownTimer=null,nextHandTimer=null;
const $=id=>document.getElementById(id),E={connectionStatus:$("connectionStatus"),setupPanel:$("setupPanel"),roomPanel:$("roomPanel"),hostModeButton:$("hostModeButton"),guestModeButton:$("guestModeButton"),hostSetup:$("hostSetup"),guestSetup:$("guestSetup"),hostNameInput:$("hostNameInput"),guestNameInput:$("guestNameInput"),playerCountSelect:$("playerCountSelect"),createRoomButton:$("createRoomButton"),joinRoomButton:$("joinRoomButton"),roomCodeInput:$("roomCodeInput"),roomCodeDisplay:$("roomCodeDisplay"),hostTools:$("hostTools"),roomPlayerCountSelect:$("roomPlayerCountSelect"),startGameButton:$("startGameButton"),endGameButton:$("endGameButton"),blindBadge:$("blindBadge"),handNumber:$("handNumber"),blindLevel:$("blindLevel"),aliveCount:$("aliveCount"),notice:$("notice"),streetName:$("streetName"),potValue:$("potValue"),potList:$("potList"),board:$("board"),seats:$("seats"),actionTitle:$("actionTitle"),timerText:$("timerText"),timerBar:$("timerBar"),actionArea:$("actionArea"),logList:$("logList"),toggleLogButton:$("toggleLogButton")};
const uid=p=>`${p}_${Math.random().toString(36).slice(2,10)}`,name=(v,d)=>String(v||"").trim().slice(0,12)||d,esc=v=>String(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
async function post(path,data){const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});if(!r.ok)throw new Error(await r.text());return r.json()}
async function signal(to,payload){return post("/api/signal",{roomCode,from:selfId,to,payload})}
function openEvents(id){events?.close();events=new EventSource(`/api/events?clientId=${encodeURIComponent(id)}`);events.addEventListener("signal",e=>receive(JSON.parse(e.data)));events.onopen=()=>E.connectionStatus.textContent=`已连接房间 ${roomCode}`;events.onerror=()=>E.connectionStatus.textContent="联机服务正在重连"}
function receive(msg){const p=msg.payload;if(mode==="host"&&p?.kind==="hello")return admit(msg.from,p.name);if(mode==="host"&&p?.kind==="action")return act(msg.from,p.action);if(mode==="guest"&&p?.kind==="view"){guestView=p.view;enter();render()}if(mode==="guest"&&p?.kind==="rejected"){events?.close();alert(p.message);E.connectionStatus.textContent="加入失败"}}
function setMode(m){mode=m;E.hostModeButton.classList.toggle("active",m==="host");E.guestModeButton.classList.toggle("active",m==="guest");E.hostSetup.classList.toggle("hidden",m!=="host");E.guestSetup.classList.toggle("hidden",m!=="guest")}
function enter(){E.setupPanel.classList.add("hidden");E.roomPanel.classList.remove("hidden");E.hostTools.classList.toggle("hidden",mode!=="host");E.roomCodeDisplay.textContent=roomCode}
function player(id,n,host=false){return{id,name:n,isHost:host,connected:true,chips:1000,status:"active",hole:[],folded:false,allIn:false,streetBet:0,totalBet:0,acted:false}}
async function createRoom(){selfId=uid("host");state={phase:"lobby",capacity:Number(E.playerCountSelect.value),players:[player(selfId,name(E.hostNameInput.value,"房主"),true)],handNumber:0,dealerIndex:-1,street:"waiting",board:[],deck:[],currentIndex:null,currentBet:0,lastFullRaise:20,smallBlindIndex:null,bigBlindIndex:null,actionDeadline:0,logs:[],showdown:false};try{const r=await post("/api/rooms",{hostId:selfId});roomCode=r.roomCode;E.roomPlayerCountSelect.value=state.capacity;openEvents(selfId);enter();render()}catch{alert("无法创建房间，请先运行 node game4/signal-server.js")}}
async function joinRoom(){roomCode=E.roomCodeInput.value.trim().toUpperCase();if(!/^[A-Z0-9]{4}$/.test(roomCode))return alert("请输入四位房间号。");selfId=uid("guest");try{const r=await post("/api/join",{roomCode});hostId=r.hostId;openEvents(selfId);await signal(hostId,{kind:"hello",name:name(E.guestNameInput.value,"玩家")})}catch{alert("房间不存在或联机服务未启动。")}}
function admit(id,n){if(state.phase!=="lobby")return signal(id,{kind:"rejected",message:"比赛已经开始，不允许中途加入。"});if(state.players.length>=state.capacity)return signal(id,{kind:"rejected",message:"房间人数已满。"});state.players.push(player(id,name(n,"玩家")));sync()}
function changeCapacity(){const n=Number(E.roomPlayerCountSelect.value);if(n<state.players.length){alert("人数不能少于已经加入的玩家。");E.roomPlayerCountSelect.value=state.capacity;return}state.capacity=n;sync()}
function alive(){return state.players.filter(p=>p.status==="active"&&p.chips>0)}
function nextIndex(from,predicate=p=>p.status==="active"&&p.chips>0){for(let step=1;step<=state.players.length;step++){const i=(from+step)%state.players.length;if(predicate(state.players[i]))return i}return null}
function blindInfo(){
  const level=Math.floor(Math.max(0,state.handNumber-1)/5);
  if(level<BLINDS.length)return{level:level+1,sb:BLINDS[level][0],bb:BLINDS[level][1]};
  let sb=BLINDS[BLINDS.length-1][0];
  for(let n=BLINDS.length;n<=level;n++)sb=Math.ceil(sb*1.5/50)*50;
  return{level:level+1,sb,bb:sb*2};
}
function deck(){const d=[];for(const s of SUITS)for(const r of RANKS)d.push({r,s});for(let i=d.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[d[i],d[j]]=[d[j],d[i]]}return d}
function log(text){state.logs.unshift({id:uid("log"),text});state.logs=state.logs.slice(0,80)}
function startTournament(){if(state.players.length!==state.capacity)return alert(`需要 ${state.capacity} 人到齐。`);state.phase="playing";state.players.forEach(p=>{p.chips=1000;p.status="active"});state.handNumber=0;state.dealerIndex=-1;startHand()}
function endGame(){if(mode!=="host"||!state||state.phase==="lobby")return;if(!confirm("确定结束当前游戏并返回准备阶段吗？本局筹码和成绩将被清空。"))return;clearTimeout(actionTimer);clearTimeout(nextHandTimer);state.phase="lobby";state.handNumber=0;state.dealerIndex=-1;state.street="waiting";state.board=[];state.deck=[];state.currentIndex=null;state.currentBet=0;state.lastFullRaise=20;state.smallBlindIndex=null;state.bigBlindIndex=null;state.actionDeadline=0;state.logs=[];state.showdown=false;state.players.forEach(p=>{p.chips=1000;p.status="active";p.hole=[];p.folded=false;p.allIn=false;p.streetBet=0;p.totalBet=0;p.acted=false});sync()}
function startHand(){clearTimeout(nextHandTimer);if(alive().length<=1)return finishTournament();state.handNumber++;state.showdown=false;state.street="preflop";state.board=[];state.deck=deck();state.currentBet=0;state.actionDeadline=0;state.players.forEach(p=>{p.hole=[];p.folded=p.status!=="active";p.allIn=false;p.streetBet=0;p.totalBet=0;p.acted=false});state.dealerIndex=nextIndex(state.dealerIndex);const active=alive();if(active.length===2){state.smallBlindIndex=state.dealerIndex;state.bigBlindIndex=nextIndex(state.dealerIndex)}else{state.smallBlindIndex=nextIndex(state.dealerIndex);state.bigBlindIndex=nextIndex(state.smallBlindIndex)}for(let round=0;round<2;round++)for(let step=1;step<=state.players.length;step++){const i=(state.dealerIndex+step)%state.players.length,p=state.players[i];if(p.status==="active")p.hole.push(state.deck.pop())}const b=blindInfo();postBlind(state.smallBlindIndex,b.sb,"小盲");postBlind(state.bigBlindIndex,b.bb,"大盲");state.currentBet=b.bb;state.lastFullRaise=b.bb;state.currentIndex=nextIndex(state.bigBlindIndex,p=>canAct(p));log(`第 ${state.handNumber} 手开始，盲注 ${b.sb}/${b.bb}`);afterStateChange()}
function postBlind(i,amount,label){const p=state.players[i],paid=Math.min(amount,p.chips);p.chips-=paid;p.streetBet=paid;p.totalBet=paid;if(!p.chips)p.allIn=true;log(`${p.name} 支付${label} ${paid}`)}
function canAct(p){return p.status==="active"&&!p.folded&&!p.allIn&&p.chips>0}
function live(){return state.players.filter(p=>p.status==="active"&&!p.folded)}
function submit(action){if(mode==="host")act(selfId,action);else signal(hostId,{kind:"action",action}).catch(()=>E.connectionStatus.textContent="操作发送失败")}
function act(id,a){if(state.phase!=="playing"||state.currentIndex==null)return;const p=state.players[state.currentIndex];if(p.id!==id||!canAct(p))return;const owed=Math.max(0,state.currentBet-p.streetBet);
 if(a.type==="fold"){p.folded=true;p.acted=true;log(`${p.name} 弃牌`)}
 else if(a.type==="check"&&owed===0){p.acted=true;log(`${p.name} 过牌`)}
 else if(a.type==="call"&&owed>0){const paid=Math.min(owed,p.chips);commit(p,paid);p.acted=true;log(`${p.name}${paid<owed?"全押":"跟注"} ${paid}`)}
 else if(a.type==="raise"){if(p.acted)return;let target=Math.floor(Number(a.target));const max=p.streetBet+p.chips;if(!Number.isFinite(target)||target<=state.currentBet)return;target=Math.min(target,max);const increment=target-state.currentBet,isAllIn=target===max,minimum=state.currentBet===0?blindInfo().bb:state.lastFullRaise;if(increment<minimum&&!isAllIn)return;const paid=target-p.streetBet;if(paid<=0)return;commit(p,paid);if(increment>=minimum){state.lastFullRaise=increment;state.players.forEach(x=>{if(canAct(x))x.acted=false})}state.currentBet=Math.max(state.currentBet,target);p.acted=true;log(`${p.name}${p.allIn?"全押到":state.currentBet===target?"加注到":"下注"} ${target}`)}else return;
 afterAction()}
function commit(p,amount){const paid=Math.min(amount,p.chips);p.chips-=paid;p.streetBet+=paid;p.totalBet+=paid;if(p.chips===0)p.allIn=true}
function afterAction(){clearTimeout(actionTimer);if(live().length===1)return awardUncontested();if(roundComplete())return advanceStreet();state.currentIndex=nextIndex(state.currentIndex,p=>canAct(p));afterStateChange()}
function roundComplete(){const actors=state.players.filter(canAct);if(!actors.length)return true;if(actors.length===1&&actors[0].streetBet===state.currentBet)return true;return actors.every(p=>p.acted&&p.streetBet===state.currentBet)}
function advanceStreet(){clearTimeout(actionTimer);if(state.street==="river")return showdown();state.players.forEach(p=>{p.streetBet=0;p.acted=false});state.currentBet=0;state.lastFullRaise=blindInfo().bb;if(state.street==="preflop"){state.deck.pop();state.board.push(state.deck.pop(),state.deck.pop(),state.deck.pop());state.street="flop"}else if(state.street==="flop"){state.deck.pop();state.board.push(state.deck.pop());state.street="turn"}else{state.deck.pop();state.board.push(state.deck.pop());state.street="river"}log({flop:"翻牌",turn:"转牌",river:"河牌"}[state.street]);const actors=state.players.filter(canAct);if(actors.length<=1)return advanceStreet();state.currentIndex=nextIndex(state.dealerIndex,p=>canAct(p));afterStateChange()}
function afterStateChange(){if(state.phase!=="playing")return sync();const p=state.players[state.currentIndex];if(!p||!canAct(p)){if(roundComplete())return advanceStreet();state.currentIndex=nextIndex(state.currentIndex,p=>canAct(p))}state.actionDeadline=Date.now()+60000;sync();clearTimeout(actionTimer);actionTimer=setTimeout(autoAction,60050)}
function autoAction(){if(mode!=="host"||state.phase!=="playing"||state.currentIndex==null)return;const p=state.players[state.currentIndex],owed=Math.max(0,state.currentBet-p.streetBet);act(p.id,{type:owed===0?"check":"fold"})}
function awardUncontested(){const winner=live()[0],pot=state.players.reduce((s,p)=>s+p.totalBet,0);winner.chips+=pot;log(`${winner.name} 赢得底池 ${pot}（其他玩家均弃牌）`);endHand(false)}
function pots(){const levels=[...new Set(state.players.map(p=>p.totalBet).filter(Boolean))].sort((a,b)=>a-b);let prev=0;return levels.map(level=>{const contributors=state.players.filter(p=>p.totalBet>=level),amount=(level-prev)*contributors.length,eligible=contributors.filter(p=>!p.folded&&p.status==="active").map(p=>p.id);prev=level;return{amount,eligible}}).filter(p=>p.amount>0)}
function showdown(){state.showdown=true;const allPots=pots();for(const pot of allPots){const candidates=state.players.filter(p=>pot.eligible.includes(p.id));if(!candidates.length)continue;let best=null,winners=[];for(const p of candidates){const rank=evaluate([...p.hole,...state.board]);if(!best||compareRank(rank,best)>0){best=rank;winners=[p]}else if(compareRank(rank,best)===0)winners.push(p)}const share=Math.floor(pot.amount/winners.length),remainder=pot.amount%winners.length;winners.forEach(p=>p.chips+=share);for(let n=0;n<remainder;n++){const i=nextWinningFromDealer(winners,n);i.chips++}log(`${winners.map(p=>p.name).join("、")} 以${rankName(best)}赢得 ${pot.amount}`)}endHand(true)}
function nextWinningFromDealer(winners,offset){const ordered=[];for(let step=1;step<=state.players.length;step++){const p=state.players[(state.dealerIndex+step)%state.players.length];if(winners.includes(p))ordered.push(p)}return ordered[offset%ordered.length]}
function endHand(show){clearTimeout(actionTimer);state.currentIndex=null;state.actionDeadline=0;state.showdown=show;state.players.forEach(p=>{if(p.chips===0){p.status="eliminated";log(`${p.name} 被淘汰`)}});sync();if(alive().length<=1){nextHandTimer=setTimeout(finishTournament,3500)}else nextHandTimer=setTimeout(startHand,5000)}
function finishTournament(){clearTimeout(actionTimer);clearTimeout(nextHandTimer);state.phase="ended";state.currentIndex=null;state.actionDeadline=0;const winner=alive()[0];if(winner)log(`${winner.name} 获得锦标赛冠军！`);sync()}
function evaluate(cards){let best=null;for(let a=0;a<cards.length-4;a++)for(let b=a+1;b<cards.length-3;b++)for(let c=b+1;c<cards.length-2;c++)for(let d=c+1;d<cards.length-1;d++)for(let e=d+1;e<cards.length;e++){const r=five([cards[a],cards[b],cards[c],cards[d],cards[e]]);if(!best||compareRank(r,best)>0)best=r}return best}
function five(cards){const rs=cards.map(c=>c.r).sort((a,b)=>b-a),counts={};rs.forEach(r=>counts[r]=(counts[r]||0)+1);const groups=Object.entries(counts).map(([r,n])=>({r:+r,n})).sort((a,b)=>b.n-a.n||b.r-a.r),flush=cards.every(c=>c.s===cards[0].s),unique=[...new Set(rs)],straightHigh=unique.includes(14)&&[5,4,3,2].every(r=>unique.includes(r))?5:(unique.length===5&&unique[0]-unique[4]===4?unique[0]:0);if(flush&&straightHigh)return[8,straightHigh];if(groups[0].n===4)return[7,groups[0].r,groups[1].r];if(groups[0].n===3&&groups[1].n===2)return[6,groups[0].r,groups[1].r];if(flush)return[5,...rs];if(straightHigh)return[4,straightHigh];if(groups[0].n===3)return[3,groups[0].r,...groups.slice(1).map(g=>g.r).sort((a,b)=>b-a)];if(groups[0].n===2&&groups[1].n===2){const pairs=[groups[0].r,groups[1].r].sort((a,b)=>b-a);return[2,...pairs,groups[2].r]}if(groups[0].n===2)return[1,groups[0].r,...groups.slice(1).map(g=>g.r).sort((a,b)=>b-a)];return[0,...rs]}
function compareRank(a,b){for(let i=0;i<Math.max(a.length,b.length);i++){const d=(a[i]||0)-(b[i]||0);if(d)return d}return 0}
function rankName(r){return["高牌","一对","两对","三条","顺子","同花","葫芦","四条","同花顺"][r[0]]}
function buildView(viewer){const reveal=state.showdown||state.phase==="ended";return{selfId:viewer,phase:state.phase,capacity:state.capacity,handNumber:state.handNumber,dealerIndex:state.dealerIndex,street:state.street,board:state.board,currentIndex:state.currentIndex,currentBet:state.currentBet,lastFullRaise:state.lastFullRaise,smallBlindIndex:state.smallBlindIndex,bigBlindIndex:state.bigBlindIndex,actionDeadline:state.actionDeadline,showdown:state.showdown,blind:blindInfo(),logs:state.logs,pots:pots(),players:state.players.map((p,i)=>({...p,hole:p.id===viewer||(reveal&&!p.folded)?p.hole:p.hole.map(()=>null),seat:i}))}}
function view(){return mode==="host"?(state?buildView(selfId):null):guestView}
function broadcast(){if(mode!=="host")return;state.players.filter(p=>p.id!==selfId).forEach(p=>signal(p.id,{kind:"view",view:buildView(p.id)}).catch(()=>{p.connected=false;if(state.currentIndex!=null&&state.players[state.currentIndex].id===p.id)autoAction()}))}
function sync(){render();broadcast()}
function cardHtml(c){if(c===null)return`<div class="card back"></div>`;if(!c)return`<div class="card empty"></div>`;const red=c.s==="♥"||c.s==="♦",r={11:"J",12:"Q",13:"K",14:"A"}[c.r]||c.r;return`<div class="card ${red?"red":""}"><span class="rank">${r}</span><span class="suit">${c.s}</span></div>`}
function render(){const v=view();if(!v)return;const me=v.players.find(p=>p.id===v.selfId),current=v.players[v.currentIndex],pot=v.players.reduce((s,p)=>s+p.totalBet,0),activeCount=v.players.filter(p=>p.status==="active").length;E.roomCodeDisplay.textContent=roomCode;E.roomPlayerCountSelect.value=v.capacity;E.roomPlayerCountSelect.disabled=v.phase!=="lobby";E.startGameButton.disabled=v.players.length!==v.capacity;E.startGameButton.classList.toggle("hidden",v.phase!=="lobby");E.endGameButton.classList.toggle("hidden",v.phase==="lobby");E.blindBadge.textContent=`${v.blind.sb} / ${v.blind.bb}`;E.handNumber.textContent=v.handNumber;E.blindLevel.textContent=v.blind.level;E.aliveCount.textContent=activeCount;E.potValue.textContent=pot;E.streetName.textContent={waiting:"等待开局",preflop:"翻牌前",flop:"翻牌",turn:"转牌",river:"河牌"}[v.street]||"摊牌";E.board.innerHTML=Array.from({length:5},(_,i)=>cardHtml(v.board[i])).join("");E.potList.textContent=v.pots.length>1?v.pots.map((p,i)=>`${i?`边池 ${i}`:"主池"}：${p.amount}`).join(" · "):"";
 E.seats.innerHTML=v.players.map((p,i)=>`<div class="seat ${i===v.currentIndex?"turn":""} ${p.folded?"folded":""} ${p.status!=="active"?"out":""}"><div class="seat-top"><span class="seat-name">${esc(p.name)}</span><span class="chips">${p.chips}</span></div><div class="seat-meta">${i===v.dealerIndex?'<i class="dealer">D</i>':""}${i===v.smallBlindIndex?'<i class="blind-tag">SB</i>':""}${i===v.bigBlindIndex?'<i class="blind-tag">BB</i>':""}${p.allIn?'<i class="allin">ALL IN</i>':""}${p.status==="eliminated"?"已淘汰":p.folded?"已弃牌":p.streetBet?`本轮 ${p.streetBet}`:""}</div><div class="hole">${p.hole.map(cardHtml).join("")}</div></div>`).join("");
 if(v.phase==="lobby")E.notice.textContent=v.players.length===v.capacity?"玩家到齐，房主可以开始锦标赛。":`等待玩家加入：${v.players.length}/${v.capacity}`;else if(v.phase==="ended"){const w=v.players.find(p=>p.status==="active");E.notice.textContent=`锦标赛结束，${w?.name||"玩家"} 获得冠军！`}else E.notice.textContent=v.showdown?"本手牌结算完成，5 秒后开始下一手。":`第 ${v.handNumber} 手 · 盲注 ${v.blind.sb}/${v.blind.bb}`;
 renderActions(v,me,current);E.logList.innerHTML=v.logs.map(x=>`<div class="log-item">${esc(x.text)}</div>`).join("");startCountdown(v)}
function renderActions(v,me,current){if(v.phase!=="playing"||v.currentIndex==null){E.actionTitle.textContent=v.phase==="ended"?"锦标赛结束":v.showdown?"正在结算":"等待开始";E.actionArea.innerHTML="";return}E.actionTitle.textContent=`轮到 ${current.name}`;if(current.id!==v.selfId){E.actionArea.innerHTML='<span class="player-meta">等待当前玩家操作…</span>';return}const owed=Math.max(0,v.currentBet-me.streetBet),max=me.streetBet+me.chips,min=v.currentBet===0?v.blind.bb:v.currentBet+v.lastFullRaise,actualMin=Math.min(min,max),rangeHint=max<min?`仅可全押至 ${max}`:`可用范围：${actualMin} – ${max}`,canRaise=!me.acted&&max>v.currentBet;E.actionArea.innerHTML=`<button id="foldButton" class="danger">弃牌</button>${owed===0?'<button id="checkButton" class="primary">过牌</button>':`<button id="callButton" class="primary">跟注 ${Math.min(owed,me.chips)}${me.chips<=owed?"（全押）":""}</button>`}${canRaise?`<label>${v.currentBet===0?"下注到":"加注到"}<input id="raiseInput" type="number" min="${actualMin}" max="${max}" value="${Math.min(Math.max(min,v.blind.bb),max)}"><span class="bet-range">${rangeHint}</span></label><div class="quick-bets"><button data-quick="half">1/2池</button><button data-quick="pot">1倍池</button><button data-quick="all">全押</button></div><button id="raiseButton">${max<min?"全押":"确认"}</button>`:""}`;$("foldButton").onclick=()=>submit({type:"fold"});if($("checkButton"))$("checkButton").onclick=()=>submit({type:"check"});if($("callButton"))$("callButton").onclick=()=>submit({type:"call"});if($("raiseButton"))$("raiseButton").onclick=()=>submit({type:"raise",target:Number($("raiseInput").value)});E.actionArea.querySelectorAll("[data-quick]").forEach(b=>b.onclick=()=>{const base=b.dataset.quick==="all"?max:b.dataset.quick==="pot"?me.streetBet+owed+potAfterCall(v,me):me.streetBet+owed+Math.floor(potAfterCall(v,me)/2);$("raiseInput").value=Math.min(max,Math.max(min,base))})}
function potAfterCall(v,me){return v.players.reduce((s,p)=>s+p.totalBet,0)+Math.min(Math.max(0,v.currentBet-me.streetBet),me.chips)}
function startCountdown(v){clearInterval(countdownTimer);const update=()=>{if(!v.actionDeadline){E.timerText.textContent="--";E.timerBar.style.width="0";return}const left=Math.max(0,v.actionDeadline-Date.now()),sec=Math.ceil(left/1000);E.timerText.textContent=`${sec}s`;E.timerBar.style.width=`${left/600}%`};update();countdownTimer=setInterval(update,250)}
async function init(){try{if((await fetch("/api/config",{cache:"no-store"})).ok)E.connectionStatus.textContent="联机服务可用"}catch{E.connectionStatus.textContent="请通过 signal-server.js 打开"}E.hostModeButton.onclick=()=>setMode("host");E.guestModeButton.onclick=()=>setMode("guest");E.createRoomButton.onclick=createRoom;E.joinRoomButton.onclick=joinRoom;E.roomCodeInput.oninput=()=>E.roomCodeInput.value=E.roomCodeInput.value.toUpperCase().replace(/[^A-Z0-9]/g,"");E.roomPlayerCountSelect.onchange=changeCapacity;E.startGameButton.onclick=startTournament;E.endGameButton.onclick=endGame;E.toggleLogButton.onclick=()=>E.logList.classList.toggle("collapsed");setMode("host")}
init();
