"use strict";
const fs=require("fs"),http=require("http"),path=require("path");const{URL}=require("url");
const port=Number(process.env.PORT||8790),root=__dirname,rooms=new Map(),clients=new Map(),pending=new Map(),alphabet="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
function json(res,status,data){res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"});res.end(JSON.stringify(data))}
function body(req){return new Promise((resolve,reject)=>{let value="";req.on("data",c=>{value+=c;if(value.length>1048576){req.destroy();reject(new Error("body too large"))}});req.on("end",()=>{try{resolve(value?JSON.parse(value):{})}catch(e){reject(e)}})})}
function roomCode(){for(let n=0;n<100;n++){let code="";for(let i=0;i<4;i++)code+=alphabet[Math.floor(Math.random()*alphabet.length)];if(!rooms.has(code))return code}throw new Error("cannot allocate room")}
function push(id,event,data){const client=clients.get(id);if(!client){const queue=pending.get(id)||[];queue.push({event,data});pending.set(id,queue.slice(-60));return false}client.res.write(`event: ${event}\n`);client.res.write(`data: ${JSON.stringify(data)}\n\n`);return true}
function staticFile(res,pathname){const target=pathname==="/"?path.join(root,"index.html"):path.join(root,pathname),resolved=path.resolve(target);if(resolved!==root&&!resolved.startsWith(root+path.sep)){res.writeHead(403);res.end("Forbidden");return}fs.readFile(resolved,(e,data)=>{if(e){res.writeHead(404);res.end("Not found");return}const type={".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"text/javascript; charset=utf-8"}[path.extname(resolved)]||"application/octet-stream";res.writeHead(200,{"Content-Type":type,"Cache-Control":"no-store"});res.end(data)})}
async function api(req,res,url){if(req.method==="GET"&&url.pathname==="/api/config"){json(res,200,{relayMode:true});return}if(req.method==="GET"&&url.pathname==="/api/events"){const id=url.searchParams.get("clientId");if(!id){json(res,400,{error:"clientId required"});return}res.writeHead(200,{"Content-Type":"text/event-stream; charset=utf-8","Cache-Control":"no-store",Connection:"keep-alive"});res.write(": connected\n\n");const heartbeat=setInterval(()=>res.write(": heartbeat\n\n"),15000);clients.set(id,{res,heartbeat});(pending.get(id)||[]).forEach(item=>push(id,item.event,item.data));pending.delete(id);req.on("close",()=>{const client=clients.get(id);if(client?.res===res){clearInterval(client.heartbeat);clients.delete(id)}});return}if(req.method==="POST"&&url.pathname==="/api/rooms"){const data=await body(req);if(!data.hostId){json(res,400,{error:"hostId required"});return}const code=roomCode();rooms.set(code,{hostId:data.hostId});json(res,200,{roomCode:code});return}if(req.method==="POST"&&url.pathname==="/api/join"){const data=await body(req),code=String(data.roomCode||"").toUpperCase(),room=rooms.get(code);if(!room){json(res,404,{error:"room not found"});return}json(res,200,{roomCode:code,hostId:room.hostId});return}if(req.method==="POST"&&url.pathname==="/api/signal"){const data=await body(req),code=String(data.roomCode||"").toUpperCase();if(!rooms.has(code)){json(res,404,{error:"room not found"});return}json(res,200,{delivered:push(data.to,"signal",{roomCode:code,from:data.from,payload:data.payload})});return}json(res,404,{error:"not found"})}
const server=http.createServer((req,res)=>{const url=new URL(req.url,`http://${req.headers.host}`);if(url.pathname.startsWith("/api/")){api(req,res,url).catch(e=>json(res,500,{error:e.message}));return}staticFile(res,decodeURIComponent(url.pathname))});
server.listen(port,()=>{console.log(`Texas Hold'em: http://localhost:${port}`);console.log("Network mode: host-authoritative HTTP + SSE relay")});
